"""added status column in task event

Revision ID: 02303c8d9ca8
Revises: 2f9fbb34e033
Create Date: 2023-08-10 14:40:42.799965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02303c8d9ca8'
down_revision = '2f9fbb34e033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE statusenum AS ENUM('NOT_STARTED', 'INPROGRESS', 'COMPLETED')")
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('NOT_STARTED', 'INPROGRESS', 'COMPLETED', name='statusenum'), nullable=True))
        batch_op.drop_column('is_completed')

    with op.batch_alter_table('task_events_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('NOT_STARTED', 'INPROGRESS', 'COMPLETED', name='statusenum'), autoincrement=False, nullable=True))
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_events_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
