"""Add Not applicable ministry in ministries table

Revision ID: 09a79ca8e8fd
Revises: 65cb91595d6a
Create Date: 2024-01-11 13:19:49.744798

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '09a79ca8e8fd'
down_revision = '65cb91595d6a'
branch_labels = None
depends_on = None

na_ministry_name = 'Not Applicable'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(f"""
        INSERT INTO ministries (name, abbreviation, is_active, is_deleted, sort_order)
        SELECT '{na_ministry_name}', 'NA', true, false, -1
        WHERE NOT EXISTS (SELECT 1 FROM ministries WHERE name='{na_ministry_name}');
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(f"delete from ministries where name='{na_ministry_name}'")

    # ### end Alembic commands ###
