"""Add Not applicable ministry in ministries table

Revision ID: 09a79ca8e8fd
Revises: 65cb91595d6a
Create Date: 2024-01-11 13:19:49.744798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a79ca8e8fd'
down_revision = '65cb91595d6a'
branch_labels = None
depends_on = None

NoneMinistryName = 'Not Applicable'
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(sa.text("""
        INSERT INTO ministries (name, abbreviation, is_active, is_deleted, sort_order)
        VALUES (:name, :abbreviation, :is_active, :is_deleted, :sort_order)
        ON CONFLICT (name) DO NOTHING;
    """).bindparams(
        name=NoneMinistryName,
        abbreviation=NoneMinistryName,
        is_active=True,
        is_deleted=False,
        sort_order=-1
    ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(f"delete from ministries where name='{NoneMinistryName}'")

    # ### end Alembic commands ###
