"""clearing history

Revision ID: 2f9fbb34e033
Revises: 2245335bd765
Create Date: 2023-08-10 13:35:36.628865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9fbb34e033'
down_revision = '2245335bd765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE events_history CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
