"""Add approved date column to work_statuses

Revision ID: 3e98650b385c
Revises: 6a490ab27bd8
Create Date: 2023-11-22 19:24:11.850442

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3e98650b385c'
down_revision = '6a490ab27bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('work_statuses_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_statuses_history', schema=None) as batch_op:
        batch_op.drop_column('approved_date')

    with op.batch_alter_table('work_statuses', schema=None) as batch_op:
        batch_op.drop_column('approved_date')

    # ### end Alembic commands ###
