"""act_sections

Revision ID: 4b5f3a264271
Revises: 449afdbe4d0d
Create Date: 2023-10-24 21:24:14.502652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5f3a264271'
down_revision = '449afdbe4d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('act_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ea_act_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'ea_acts', ['ea_act_id'], ['id'])

    with op.batch_alter_table('act_sections_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ea_act_id', sa.Integer(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(None, 'ea_acts', ['ea_act_id'], ['id'])
    for sort_order, act in enumerate(["Time Limit Extension 38(1)(a)", "Time Limit Suspension 45(1)"]):
        op.execute(f"INSERT INTO act_sections(name, ea_act_id, sort_order)VALUES('{act}',3,{sort_order + 1})")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('act_sections_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ea_act_id')

    with op.batch_alter_table('act_sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ea_act_id')

    # ### end Alembic commands ###
