"""added decision_by_id fields to works

Revision ID: 622cb040a90e
Revises: 2b164207f899
Create Date: 2023-02-02 11:38:06.597732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622cb040a90e'
down_revision = '2b164207f899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE works RESTART IDENTITY CASCADE')
    op.add_column('work_statuses', sa.Column('work_status_notes', sa.Text(), nullable=True))
    op.add_column('works', sa.Column('eac_decision_by_id', sa.Integer(), nullable=False))
    op.add_column('works', sa.Column('decision_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'works', 'staffs', ['decision_by_id'], ['id'])
    op.create_foreign_key(None, 'works', 'staffs', ['eac_decision_by_id'], ['id'])
    op.drop_column('works', 'work_status_notes')
    op.drop_column('works', 'work_short_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('work_short_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('work_status_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_column('works', 'decision_by_id')
    op.drop_column('works', 'eac_decision_by_id')
    op.drop_column('work_statuses', 'work_status_notes')
    # ### end Alembic commands ###
