"""add REL role

Revision ID: 6d65d9ec068b
Revises: 04f2481b1718
Create Date: 2026-03-17 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d65d9ec068b'
down_revision = '04f2481b1718'
branch_labels = None
depends_on = None
rel_role = 'REL'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    roles = sa.Table(
        'roles',
        sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('sort_order', sa.Integer, nullable=False),
    )

    op.bulk_insert(roles, [
                   {'name': rel_role, 'sort_order': 6},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DELETE FROM roles WHERE name = '{rel_role}'")
    # ### end Alembic commands ###
