"""phases
Revision ID: 6e3b2b3e56f0
Revises: 51ebcf9d0049
Create Date: 2022-02-14 15:03:53.139327
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6e3b2b3e56f0'
down_revision = '51ebcf9d0049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    phase_code = op.create_table('phase_codes',
                                 sa.Column('sort_order', sa.Integer(), nullable=True),
                                 sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                 sa.Column('work_type_id', sa.Integer(), nullable=False),
                                 sa.Column('start_event', sa.String(), nullable=True),
                                 sa.Column('end_event', sa.String(), nullable=True),
                                 sa.Column('duration', sa.Integer(), nullable=True),
                                 sa.Column('legislated', sa.Boolean(), nullable=True),
                                 sa.Column('name', sa.String(), nullable=True),
                                 sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], ),
                                 sa.PrimaryKeyConstraint('id')
                                 )
    ea_act = op.create_table('ea_acts',
                                sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                sa.Column('name', sa.String(), nullable=False),
                                sa.PrimaryKeyConstraint('id')
                                 )
    ministry = op.create_table('ministries',
                                sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                sa.Column('name', sa.String(), nullable=False),
                                sa.Column('abbreviation', sa.String),
                                sa.PrimaryKeyConstraint('id')
                               )
    federal_involvement = op.create_table('federal_involvements',
                                sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                sa.Column('name', sa.String(), nullable=False),
                                sa.PrimaryKeyConstraint('id')
                                )
    sector = op.create_table('sectors',
                                sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                sa.Column('name', sa.String(), nullable=False),
                                sa.Column('short_name',sa.String,nullable=False),
                                sa.PrimaryKeyConstraint('id')
                                )
    sub_sector = op.create_table('sub_sectors',
                                sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                sa.Column('sector_id', sa.Integer(), nullable=False),
                                sa.Column('name', sa.String(), nullable=False),
                                sa.Column('short_name', sa.String(), nullable=False),
                                sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
                                sa.PrimaryKeyConstraint('id')
                                )
    proponent = op.create_table('proponents',
                                sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                sa.Column('name', sa.String(), nullable=False),
                                sa.Column('is_active',sa.BOOLEAN,nullable=False,default=False),
                                sa.PrimaryKeyConstraint('id')
                                )
    region = op.create_table('regions',
                                sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                sa.Column('name', sa.String(), nullable=False),
                                sa.Column('entity',sa.String(),nullable=False),
                                sa.PrimaryKeyConstraint('id'))
    op.bulk_insert(region,
    [
        {
        "name": "Cariboo",
        "entity": "ENV"
        },
        {
        "name": "Kootenay",
        "entity": "ENV"
        },
        {
        "name": "Lower Mainland",
        "entity": "ENV"
        },
        {
        "name": "Okanagan",
        "entity": "ENV"
        },
        {
        "name": "Omineca",
        "entity": "ENV"
        },
        {
        "name": "Peace",
        "entity": "ENV"
        },
        {
        "name": "Skeena",
        "entity": "ENV"
        },
        {
        "name": "Thompson",
        "entity": "ENV"
        },
        {
        "name": "Vancouver Island",
        "entity": "ENV"
        },
        {
        "name": "Cariboo",
        "entity": "FLNR"
        },
        {
        "name": "Kootenay-Boundary",
        "entity": "FLNR"
        },
        {
        "name": "Northeast",
        "entity": "FLNR"
        },
        {
        "name": "Omineca",
        "entity": "FLNR"
        },
        {
        "name": "Skeena",
        "entity": "FLNR"
        },
        {
        "name": "South Coast",
        "entity": "FLNR"
        },
        {
        "name": "Thompson-Okanagan",
        "entity": "FLNR"
        },
        {
        "name": "West Coast",
        "entity": "FLNR"
        }
  ])
    op.bulk_insert(proponent,
    [
        {
        "name": "445026 BC Limited",
        "is_active": False
        },
        {
        "name": "622664 BC Limited",
        "is_active": False
        },
        {
        "name": "AES Wapiti Energy Corporation",
        "is_active": False
        },
        {
        "name": "Air Liquide Canada Inc.",
        "is_active": False
        },
        {
        "name": "Alaska Hydro Corporation",
        "is_active": False
        },
        {
        "name": "Aley Corporation Limited",
        "is_active": False
        },
        {
        "name": "AltaGas Renewable Energy Incorporated",
        "is_active": False
        },
        {
        "name": "Alterra Power Corporation",
        "is_active": False
        },
        {
        "name": "Arctos Anthracite Joint Venture",
        "is_active": False
        },
        {
        "name": "Ascot Resources Limited",
        "is_active": False
        },
        {
        "name": "AuRico Metals Incorporated",
        "is_active": False
        },
        {
        "name": "Aurora Liquefied Natural Gas Limited",
        "is_active": False
        },
        {
        "name": "Avanti Kitsault Mine Limited",
        "is_active": False
        },
        {
        "name": "Babkirk Land Services Incorporated",
        "is_active": False
        },
        {
        "name": "Barkerville Gold Mines Ltd.",
        "is_active": True
        },
        {
        "name": "BC Gas Utility Limited",
        "is_active": False
        },
        {
        "name": "BC Hydro and Power Authority",
        "is_active": False
        },
        {
        "name": "bcMetals Corporation",
        "is_active": False
        },
        {
        "name": "Bear Mountain Wind Limited Partnership",
        "is_active": False
        },
        {
        "name": "Belkorp Environmental Services Incorporated and the Village of Cache Creek",
        "is_active": False
        },
        {
        "name": "Big Silver Creek Power Limited Partnership",
        "is_active": False
        },
        {
        "name": "Black Mountain Irrigation District",
        "is_active": False
        },
        {
        "name": "Brilliant Expansion Power Corporation",
        "is_active": False
        },
        {
        "name": "British Columbia Transmission Corporation",
        "is_active": False
        },
        {
        "name": "BURNCO Rock Products Limited",
        "is_active": False
        },
        {
        "name": "BW Gold Ltd.",
        "is_active": False
        },
        {
        "name": "Canada Line Rapid Transit Incorporated",
        "is_active": False
        },
        {
        "name": "Canadian Forest Products Limited",
        "is_active": False
        },
        {
        "name": "Canadian Hunter Exploration Limited",
        "is_active": False
        },
        {
        "name": "Canadian Natural Resources",
        "is_active": False
        },
        {
        "name": "CanLava Mining Corporation",
        "is_active": False
        },
        {
        "name": "Capital Power L.P.",
        "is_active": False
        },
        {
        "name": "Capital Regional District",
        "is_active": False
        },
        {
        "name": "Cardero Coal Limited",
        "is_active": False
        },
        {
        "name": "CCS Corporation",
        "is_active": False
        },
        {
        "name": "Cedar LNG Export Development Ltd.",
        "is_active": False
        },
        {
        "name": "Centermount Coal Limited",
        "is_active": False
        },
        {
        "name": "CertainTeed Canada Inc.",
        "is_active": False
        },
        {
        "name": "Chieftain Metals Incorporated",
        "is_active": False
        },
        {
        "name": "Cirque Operation Corporation",
        "is_active": False
        },
        {
        "name": "City of Abbotsford",
        "is_active": False
        },
        {
        "name": "City of Burnaby",
        "is_active": False
        },
        {
        "name": "City of Campbell River",
        "is_active": False
        },
        {
        "name": "City of Chilliwack",
        "is_active": False
        },
        {
        "name": "City of Cranbrook",
        "is_active": False
        },
        {
        "name": "City of Fernie",
        "is_active": False
        },
        {
        "name": "City of Kamloops",
        "is_active": False
        },
        {
        "name": "City of Prince George",
        "is_active": False
        },
        {
        "name": "City of Quesnel",
        "is_active": False
        },
        {
        "name": "City of Terrace",
        "is_active": False
        },
        {
        "name": "City of Williams Lake",
        "is_active": False
        },
        {
        "name": "CKD Mines Co. Ltd.",
        "is_active": False
        },
        {
        "name": "Cline Mining Corporation",
        "is_active": False
        },
        {
        "name": "Coast Mountain Hydro Corporation",
        "is_active": False
        },
        {
        "name": "Coastal GasLink Pipeline Limited",
        "is_active": False
        },
        {
        "name": "Columbia Power Corporation",
        "is_active": False
        },
        {
        "name": "Comox Valley Regional District",
        "is_active": False
        },
        {
        "name": "Compliance Coal Corporation",
        "is_active": False
        },
        {
        "name": "Compliance Power Corporation",
        "is_active": False
        },
        {
        "name": "Construction Aggregates Limited",
        "is_active": False
        },
        {
        "name": "Conuma Coal Resources Limited",
        "is_active": False
        },
        {
        "name": "Covanta Energy Corporation",
        "is_active": False
        },
        {
        "name": "District of Mission",
        "is_active": False
        },
        {
        "name": "District of North Cowichan",
        "is_active": False
        },
        {
        "name": "District of Squamish",
        "is_active": False
        },
        {
        "name": "Doublestar Resources Limited",
        "is_active": False
        },
        {
        "name": "Duke Energy",
        "is_active": False
        },
        {
        "name": "Dunkley Lumber Limited",
        "is_active": False
        },
        {
        "name": "Eagle Rock Materials Limited",
        "is_active": False
        },
        {
        "name": "EarthFirst Canada Inc.",
        "is_active": False
        },
        {
        "name": "Elk Valley Coal Corporation",
        "is_active": False
        },
        {
        "name": "Elkview Coal Corporation",
        "is_active": False
        },
        {
        "name": "Enbridge Frontier Inc.",
        "is_active": False
        },
        {
        "name": "Enbridge G&P Canada Limited Partnership",
        "is_active": False
        },
        {
        "name": "Encana Corporation",
        "is_active": False
        },
        {
        "name": "EnviroFor Preservers (BC) Limited",
        "is_active": False
        },
        {
        "name": "Ferus Group of Companies",
        "is_active": False
        },
        {
        "name": "Finavera Wind Energy Incorporated",
        "is_active": False
        },
        {
        "name": "FortisBC",
        "is_active": False
        },
        {
        "name": "Fortune Coal Limited",
        "is_active": False
        },
        {
        "name": "Fraser Bridge Project Limited",
        "is_active": False
        },
        {
        "name": "Galore Creek Mining Corporation",
        "is_active": False
        },
        {
        "name": "Garibaldi at Squamish Incorporated",
        "is_active": False
        },
        {
        "name": "Glacier Aggregates Incorporated",
        "is_active": False
        },
        {
        "name": "Glacier Resorts Limited",
        "is_active": False
        },
        {
        "name": "Glencore plc",
        "is_active": False
        },
        {
        "name": "Global Container Terminals",
        "is_active": False
        },
        {
        "name": "Global Drilling Solutions Incorporated",
        "is_active": False
        },
        {
        "name": "Graymont Western Canada Incorporated",
        "is_active": False
        },
        {
        "name": "Greater Vancouver Sewerage and Drainage District",
        "is_active": False
        },
        {
        "name": "Hackney Hills Wind Limited Partnership",
        "is_active": False
        },
        {
        "name": "Harper Creek Mining Corporation",
        "is_active": False
        },
        {
        "name": "Hawkeye Energy Corporation",
        "is_active": False
        },
        {
        "name": "HD Mining International Limited",
        "is_active": False
        },
        {
        "name": "Highland Valley Copper Corporation",
        "is_active": False
        },
        {
        "name": "Hillsborough Resources Limited",
        "is_active": False
        },
        {
        "name": "Holberg Wind Energy GP Incorporated",
        "is_active": False
        },
        {
        "name": "Homestake Canada Incorporated",
        "is_active": False
        },
        {
        "name": "Huckleberry Mines Limited",
        "is_active": False
        },
        {
        "name": "IDM Mining Limited",
        "is_active": False
        },
        {
        "name": "Imperial Metals Corporation",
        "is_active": False
        },
        {
        "name": "Innergex Renewable Energy Incorporated",
        "is_active": False
        },
        {
        "name": "International Wayside Gold Mines Limited",
        "is_active": False
        },
        {
        "name": "Interoute Construction Limited",
        "is_active": False
        },
        {
        "name": "Invenergy LLC",
        "is_active": False
        },
        {
        "name": "Kamloops Airport Authority Society",
        "is_active": False
        },
        {
        "name": "Keyspan Energy Canada Company",
        "is_active": False
        },
        {
        "name": "KGHM Ajax Mining Incorporated",
        "is_active": False
        },
        {
        "name": "Kitamaat Renewable Energy Corporation",
        "is_active": False
        },
        {
        "name": "Kitimat Clean Limited",
        "is_active": False
        },
        {
        "name": "Kleana Power Corporation",
        "is_active": False
        },
        {
        "name": "KM LNG Operating Partnership",
        "is_active": False
        },
        {
        "name": "Kruger Energy Isle Pierre Limited Partnership",
        "is_active": False
        },
        {
        "name": "KSM Mining ULC",
        "is_active": False
        },
        {
        "name": "Kutcho Copper Corporation",
        "is_active": False
        },
        {
        "name": "Kwagis Power Limited Partnership",
        "is_active": False
        },
        {
        "name": "Kwantlen First Nation",
        "is_active": False
        },
        {
        "name": "Kwiakah First Nation, Da'naxda'xw/Awaetlala First Nation",
        "is_active": False
        },
        {
        "name": "Kwispaa LNG (CF) Limited Partnership",
        "is_active": False
        },
        {
        "name": "Kwoiek Creek Resources Limited Partnership",
        "is_active": False
        },
        {
        "name": "Lafarge Canada Incorporated",
        "is_active": False
        },
        {
        "name": "Lehigh Hanson Materials Limited",
        "is_active": False
        },
        {
        "name": "Line Creek Mine Limited",
        "is_active": False
        },
        {
        "name": "LNG Canada Development Incorporated",
        "is_active": False
        },
        {
        "name": "Louisiana-Pacific OSB Limited Partnership",
        "is_active": False
        },
        {
        "name": "Luscar Limited",
        "is_active": False
        },
        {
        "name": "Mackenzie Green Energy Limited Partnership",
        "is_active": False
        },
        {
        "name": "McGillivray Mining Limited",
        "is_active": False
        },
        {
        "name": "Meadows Quarry Group",
        "is_active": False
        },
        {
        "name": "Meikle Wind Energy Limited Partnership",
        "is_active": False
        },
        {
        "name": "Ministry of Transportation and Infrastructure",
        "is_active": False
        },
        {
        "name": "Morrison Petroleums Limited",
        "is_active": False
        },
        {
        "name": "Mount Polley Mining Corporation",
        "is_active": False
        },
        {
        "name": "Musqueam Indian Band and Bastion Development Corporation",
        "is_active": False
        },
        {
        "name": "Nabors Drilling Canada Limited",
        "is_active": False
        },
        {
        "name": "NaiKun Wind Development Incorporated",
        "is_active": False
        },
        {
        "name": "NEMI Northern Energy and Mining Incorporated",
        "is_active": False
        },
        {
        "name": "Newcrest Red Chris Mining Limited",
        "is_active": False
        },
        {
        "name": "Newhawk Gold Mines Limited",
        "is_active": False
        },
        {
        "name": "Nexen Energy ULC",
        "is_active": False
        },
        {
        "name": "NGR Resort Consultants Incorporated",
        "is_active": False
        },
        {
        "name": "Nicola Valley Aggregates",
        "is_active": False
        },
        {
        "name": "Nomis Power Corporation",
        "is_active": False
        },
        {
        "name": "NorskeCanada",
        "is_active": False
        },
        {
        "name": "North Coal Limited",
        "is_active": False
        },
        {
        "name": "North Coast Wind Energy Corporation",
        "is_active": False
        },
        {
        "name": "North Pacific Alloys Limited",
        "is_active": False
        },
        {
        "name": "North Pacific Stone Limited",
        "is_active": False
        },
        {
        "name": "Northern Gateway Pipelines Limited Partnership",
        "is_active": False
        },
        {
        "name": "Northgate Minerals Corporation",
        "is_active": False
        },
        {
        "name": "Northland Power Incorporated",
        "is_active": False
        },
        {
        "name": "NOVA Gas Transmission Limited",
        "is_active": False
        },
        {
        "name": "Novagas Canada Limited",
        "is_active": False
        },
        {
        "name": "NWP Coal Canada Limited",
        "is_active": False
        },
        {
        "name": "Orca Sand and Gravel Limited",
        "is_active": False
        },
        {
        "name": "Pacific Booker Minerals Incorporated",
        "is_active": False
        },
        {
        "name": "Pacific Future Energy Corporation",
        "is_active": False
        },
        {
        "name": "Pacific Northern Gas Limited",
        "is_active": False
        },
        {
        "name": "Pacific Northwest LNG Limited Partnership",
        "is_active": False
        },
        {
        "name": "Pacific Trail Pipelines Limited Partnership",
        "is_active": False
        },
        {
        "name": "PAC-RIM LNG Incorporated",
        "is_active": False
        },
        {
        "name": "PAGP Partnership",
        "is_active": False
        },
        {
        "name": "Pan Pacific Aggregates Limited",
        "is_active": False
        },
        {
        "name": "PanCanadian Petroleum Limited and ATCO Power Canada Limited",
        "is_active": False
        },
        {
        "name": "Paramount Resources Limited",
        "is_active": False
        },
        {
        "name": "Parkland Refining",
        "is_active": False
        },
        {
        "name": "Peace River Coal Incorporated",
        "is_active": False
        },
        {
        "name": "Pembina Infrastructure and Logistics LP",
        "is_active": False
        },
        {
        "name": "Pembina Pipeline Corporation",
        "is_active": False
        },
        {
        "name": "PETRONAS Energy Canada Ltd.",
        "is_active": False
        },
        {
        "name": "Pingston Power Incorporated",
        "is_active": False
        },
        {
        "name": "Placer CEGO Petroleum Limited",
        "is_active": False
        },
        {
        "name": "Plateau Pipe Line Limited",
        "is_active": False
        },
        {
        "name": "Polaris Infrastructure Incorporated",
        "is_active": False
        },
        {
        "name": "Polestar Exploration Incorporated",
        "is_active": False
        },
        {
        "name": "Powerhouse Developments Incorporated",
        "is_active": False
        },
        {
        "name": "Premier Renewable Energy",
        "is_active": False
        },
        {
        "name": "Pretium Resources Inc",
        "is_active": False
        },
        {
        "name": "Prince Rupert Gas Transmission Limited",
        "is_active": False
        },
        {
        "name": "Prince Rupert LNG Limited",
        "is_active": False
        },
        {
        "name": "Purcell Green Power Incorporated",
        "is_active": False
        },
        {
        "name": "Qualark Resources Incorporated",
        "is_active": False
        },
        {
        "name": "Quinto Mining Corporation",
        "is_active": False
        },
        {
        "name": "Red Willow Wind Limited Partnership",
        "is_active": False
        },
        {
        "name": "Regional Power Incorporated",
        "is_active": False
        },
        {
        "name": "Resort Municipality of Whistler",
        "is_active": False
        },
        {
        "name": "Rigby Farmlands Limited and Little Rock Quarries",
        "is_active": False
        },
        {
        "name": "Rio Tinto Alcan",
        "is_active": False
        },
        {
        "name": "Royal Oak Mines Incorporated",
        "is_active": False
        },
        {
        "name": "Ruddock Creek Mining Corporation",
        "is_active": False
        },
        {
        "name": "Run of River Power Incorporated",
        "is_active": False
        },
        {
        "name": "Rupert Peace Power Corporation",
        "is_active": False
        },
        {
        "name": "Sea Breeze Energy Incorporated",
        "is_active": False
        },
        {
        "name": "Sea Breeze Victoria Converter Corporation",
        "is_active": False
        },
        {
        "name": "Seabird Island Band",
        "is_active": False
        },
        {
        "name": "Secure Energy Services Incorporated",
        "is_active": False
        },
        {
        "name": "Silvertip Mining Corporation",
        "is_active": False
        },
        {
        "name": "Skeena Resources Limited",
        "is_active": False
        },
        {
        "name": "Skyline Gold Corporation",
        "is_active": False
        },
        {
        "name": "Slocan Forest Products Limited",
        "is_active": False
        },
        {
        "name": "Solar Alliance Energy Incorporated",
        "is_active": False
        },
        {
        "name": "South Island Development Corporation",
        "is_active": True
        },
        {
        "name": "Spanish Mountain Gold Limited",
        "is_active": False
        },
        {
        "name": "Spectra Energy Midstream Corporation",
        "is_active": False
        },
        {
        "name": "Squamish Oceanfront Development Corporation",
        "is_active": False
        },
        {
        "name": "Squamish Terminals Ltd.",
        "is_active": False
        },
        {
        "name": "Stewart Bulk Terminals Limited",
        "is_active": False
        },
        {
        "name": "Sundance Wind Project Limited Partnership",
        "is_active": False
        },
        {
        "name": "Syntaris Power Corporation",
        "is_active": False
        },
        {
        "name": "Talisman Energy Incorporated",
        "is_active": False
        },
        {
        "name": "Taseko Mines Limited",
        "is_active": False
        },
        {
        "name": "Taylor Gas Liquids Limited Partnership",
        "is_active": False
        },
        {
        "name": "Taylor Wind Project Limited Partnership",
        "is_active": False
        },
        {
        "name": "TC Merritt Valley Farms",
        "is_active": False
        },
        {
        "name": "Teck Coal Limited",
        "is_active": False
        },
        {
        "name": "Teck Highland Valley Copper Partnership",
        "is_active": False
        },
        {
        "name": "Teck Metals Limited and BC Hydro and Power Authority",
        "is_active": False
        },
        {
        "name": "Teck Resources Limited",
        "is_active": False
        },
        {
        "name": "Telkwa Coal Limited",
        "is_active": False
        },
        {
        "name": "tems sayamkwu Limited Partnership",
        "is_active": False
        },
        {
        "name": "Terrane Metals Corporation",
        "is_active": False
        },
        {
        "name": "Tervita Corporation",
        "is_active": False
        },
        {
        "name": "Thompson Creek Metals Company",
        "is_active": False
        },
        {
        "name": "Thunder Mountain Wind Limited Partnership",
        "is_active": False
        },
        {
        "name": "Tilbury Jetty LP",
        "is_active": False
        },
        {
        "name": "Tipella Creek Project Limited Partnership, Lamont Creek Project Limited Partnership and Upper Stave Project Limited Partnership.",
        "is_active": False
        },
        {
        "name": "Toba Hydro Incorporated",
        "is_active": False
        },
        {
        "name": "Toba Montrose Hydro Incorporated",
        "is_active": False
        },
        {
        "name": "Town of Smithers",
        "is_active": False
        },
        {
        "name": "Trans Mountain Enterprises of British Columbia Limited",
        "is_active": False
        },
        {
        "name": "Trans Mountain Pipeline ULC",
        "is_active": False
        },
        {
        "name": "TransAlta Corporation",
        "is_active": False
        },
        {
        "name": "TransCanada Energy Limited",
        "is_active": False
        },
        {
        "name": "Tretheway Creek Power Limited Partnership",
        "is_active": False
        },
        {
        "name": "Tsilhqot'in Power Corporation",
        "is_active": False
        },
        {
        "name": "TTM Resources Incorporated",
        "is_active": False
        },
        {
        "name": "University of British Columbia Okanagan",
        "is_active": False
        },
        {
        "name": "Upper Lillooet River Power Limited Partnership, Boulder Creek Power Limited Partnership, North Creek Hydro Power Limited Partnership",
        "is_active": False
        },
        {
        "name": "V.I. Power Limited Partnership",
        "is_active": False
        },
        {
        "name": "Vancouver Airport Fuel Facilities Corporation",
        "is_active": False
        },
        {
        "name": "Vancouver Convention Centre Expansion Project Limited",
        "is_active": False
        },
        {
        "name": "Vancouver Fraser Port Authority",
        "is_active": False
        },
        {
        "name": "Vancouver Island Energy Corporation",
        "is_active": False
        },
        {
        "name": "VANOC 2010",
        "is_active": False
        },
        {
        "name": "Vopak Development Canada Inc.",
        "is_active": False
        },
        {
        "name": "Waneta Expansion General Partner Limited",
        "is_active": False
        },
        {
        "name": "Wartenbe Wind Project Limited Partnership",
        "is_active": False
        },
        {
        "name": "WCC LNG Project Limited",
        "is_active": False
        },
        {
        "name": "West Coast Olefins Ltd.",
        "is_active": False
        },
        {
        "name": "Westcoast Connector Gas Transmission Limited",
        "is_active": False
        },
        {
        "name": "Westcoast Gas Services Incorporated",
        "is_active": False
        },
        {
        "name": "Westcoast Power Incorporated",
        "is_active": False
        },
        {
        "name": "Westrock Industries Limited",
        "is_active": False
        },
        {
        "name": "Westscapes Development Incorporated",
        "is_active": False
        },
        {
        "name": "Weyerhaeuser Company Limited",
        "is_active": False
        },
        {
        "name": "WindRiver Power Corporation",
        "is_active": False
        },
        {
        "name": "Woodfibre LNG Limited",
        "is_active": False
        },
        {
        "name": "Woodside Energy Holdings Pty Limited",
        "is_active": False
        },
        {
        "name": "Xstrata Coal Canada Limited",
        "is_active": False
        },
        {
        "name": "Osisko Development Corporation",
        "is_active": False
        }
  ])
    op.bulk_insert(sector,
    [
        {
            'name': 'Energy - Electricity',
            'short_name': 'Energy'
        },
        {
            'name': 'Energy - Oil and Natural Gas',
            'short_name': 'O&G'
        },
        {
            'name': 'Industrial',
            'short_name': 'Industry'
        },
        {
            'name': 'Mines',
            'short_name': 'Mines'
        },
        {
            'name': 'Tourist Destination Resort',
            'short_name': 'Resorts'
        },
        {
            'name': 'Transportation',
            'short_name': 'Transport'
        },
        {
            'name': 'Waste Disposal',
            'short_name': 'Waste'
        },
        {
            'name': 'Water Management',
            'short_name': 'Water'
        },
        {
            'name': 'Other',
            'short_name': 'Other'
        }
    ])
    op.bulk_insert(sub_sector,
    [
        {
        "name": "Power Plants",
        "short_name": "Plant",
        "sector_id": 1
        },
        {
        "name": "Transmission Lines",
        "short_name": "Lines",
        "sector_id": 1
        },
        {
        "name": "Storage Facilities",
        "short_name": "Storage",
        "sector_id": 2
        },
        {
        "name": "Oil Refineries",
        "short_name": "Refinery",
        "sector_id": 2
        },
        {
        "name": "Processing Plants",
        "short_name": "Proccesing",
        "sector_id": 2
        },
        {
        "name": "Pipelines",
        "short_name": "Pipeline",
        "sector_id": 2
        },
        {
        "name": "Offshore Facilities",
        "short_name": "Offshore",
        "sector_id": 2
        },
        {
        "name": "Organic and Inorganic Chemicals",
        "short_name": "Chemicals",
        "sector_id": 3
        },
        {
        "name": "Primary Metals",
        "short_name": "Metals",
        "sector_id": 3
        },
        {
        "name": "Non-metallic Mineral Products",
        "short_name": "Non-Metallic",
        "sector_id": 3
        },
        {
        "name": "Forest Products",
        "short_name": "Forest",
        "sector_id": 3
        },
        {
        "name": "Other Industries",
        "short_name": "Other",
        "sector_id": 3
        },
        {
        "name": "Coal Mines",
        "short_name": "Coal",
        "sector_id": 4
        },
        {
        "name": "Mineral Mines",
        "short_name": "Mineral",
        "sector_id": 4
        },
        {
        "name": "Sand and Gravel Pits",
        "short_name": "Gravel",
        "sector_id": 4
        },
        {
        "name": "Placer Mineral Mines",
        "short_name": "Placer",
        "sector_id": 4
        },
        {
        "name": "Construction Stone/Industrial Minerals",
        "short_name": "Stone",
        "sector_id": 4
        },
        {
        "name": "Offshore Mines",
        "short_name": "Offshore",
        "sector_id": 4
        },
        {
        "name": "Resort Developments",
        "short_name": "Resort",
        "sector_id": 5
        },
        {
        "name": "Golf Resorts",
        "short_name": "Golf",
        "sector_id": 5
        },
        {
        "name": "Marina Resorts",
        "short_name": "Marina",
        "sector_id": 5
        },
        {
        "name": "Ski Resorts",
        "short_name": "Ski",
        "sector_id": 5
        },
        {
        "name": "Public Highways",
        "short_name": "Highway",
        "sector_id": 6
        },
        {
        "name": "Railways",
        "short_name": "Railway",
        "sector_id": 6
        },
        {
        "name": "Ferry Terminals",
        "short_name": "Ferry",
        "sector_id": 6
        },
        {
        "name": "Marine Ports",
        "short_name": "Port",
        "sector_id": 6
        },
        {
        "name": "Airports",
        "short_name": "Airport",
        "sector_id": 6
        },
        {
        "name": "Hazardous Waste Management",
        "short_name": "Hazardous",
        "sector_id": 7
        },
        {
        "name": "Solid Waste Management",
        "short_name": "Solid",
        "sector_id": 7
        },
        {
        "name": "Liquid Waste Management",
        "short_name": "Liquid",
        "sector_id": 7
        },
        {
        "name": "Dams",
        "short_name": "Dams",
        "sector_id": 8
        },
        {
        "name": "Dikes",
        "short_name": "Dikes",
        "sector_id": 8
        },
        {
        "name": "Water Diversion",
        "short_name": "Diversion",
        "sector_id": 8
        },
        {
        "name": "Groundwater Extraction",
        "short_name": "Groundwater",
        "sector_id": 8
        },
        {
        "name": "Shoreline Modification",
        "short_name": "Shoreline",
        "sector_id": 8
        },
        {
        "name": "Other",
        "short_name": "Other",
        "sector_id": 9
        }
    ])
    op.bulk_insert(
        federal_involvement,
        [            
            {
                'name':'To Be Determined'
            },
            {
                'name':'None'
            },
            {
                'name':'Comprehensive Study'
            },
            {
                'name':'Coordinated'
            },
            {
                'name':'Equivalent'
            },
            {
                'name':'Review Panel'
            },
            {
                'name':'Screening'
            },
            {
                'name':'Substituted'
            },
            {
                'name':'Harmonized'
            } 
        ]
    )
    op.bulk_insert(
        ministry,
        [
            {
                'name': 'Energy, Mines and Low Carbon Innovation',
                'abbreviation': 'EMLI'
            },
            {
                'name': 'Forests, Lands, Natural Resource Operations & Rural Development',
                'abbreviation': 'FLNR'
            },
            {
                'name': 'Jobs, Economic Recovery and Innovation',
                'abbreviation': 'JEDC'
            },
            {
                'name': 'Municipal Affairs',
                'abbreviation': 'MAH'
            },
            {
                'name': 'Transportation & Infrastructure',
                'abbreviation': 'TRAN'
            },
            {
                'name': 'Environment & Climate Change Strategy',
                'abbreviation': 'ENV Only'
            }
        ]
    )
    op.bulk_insert(
        ea_act,
        [
            {
                'name': 'EA Act (1996)',
            },
            {
                'name': 'EA Act (2002)'
            },
            {
                'name': 'EA Act (2018)'
            },
            {
                'name': 'Other'
            }
        ]
    )
    op.bulk_insert(
        phase_code,
        [
            {
                'sort_order': 1,
                'name': 'Early Engagement',
                'work_type_id': 6,
                'start_event': 'Initial Project Description accepted',
                'end_event': 'Summary of Engagement Issued',
                'duration': 90,
                'legislated': True
            },
            {
                'sort_order': 2,
                'name': 'Proponent Time: Project Description',
                'work_type_id': 6,
                'start_event': 'Day after the posting of Summary of Engagment',
                'end_event': 'Day before the submission of DPD',
                'duration': 365,
                'legislated': False
            },
            {
                'sort_order': 3,
                'name': 'Readiness Decision',
                'work_type_id': 6,
                'start_event': 'Submission of DPD',
                'end_event': 'Ministers\' Decision',
                'duration': 60,
                'legislated': False
            }, {
            'sort_order': 4,
            'name': 'Process Planning',
            'work_type_id': 6,
            'start_event': 'Day after Ministers\' Decision',
            'end_event': 'Process Order Issued',
            'duration': 120,
            'legislated': True
        }, {
            'sort_order': 5,
            'name': 'Proponent Time: Application Development',
            'work_type_id': 6,
            'start_event': 'Day after Process Order issued',
            'end_event': 'Day before the acceptance of the Application',
            'duration': 1095,
            'legislated': False
        }, {
            'sort_order': 6,
            'name': 'Application Development & Review',
            'work_type_id': 6,
            'start_event': 'Application for an EAC accepted',
            'end_event': 'Notice Regarding Application',
            'duration': 180,
            'legislated': True
        }, {
            'sort_order': 7,
            'name': 'Proponent Time: Revised Application',
            'work_type_id': 6,
            'start_event': 'Day after Notice',
            'end_event': 'Day before Revised Application',
            'duration': 365,
            'legislated': False
        }, {
            'sort_order': 8,
            'name': 'Effects Assessment',
            'work_type_id': 6,
            'start_event': 'Revised Application Submitted',
            'end_event': 'Draft Assessment Report is issued',
            'duration': 110,
            'legislated': True
        }, {
            'sort_order': 9,
            'name': 'Recommendation',
            'work_type_id': 6,
            'start_event': 'PECP starts for Draft Assessment Report?',
            'end_event': 'Package sent to Ministers',
            'duration': 40,
            'legislated': True
        }, {
            'sort_order': 10,
            'name': 'Referral/Decision',
            'work_type_id': 6,
            'start_event': 'Referral Package Received',
            'end_event': 'Minister\'s Decision',
            'duration': 30,
            'legislated': True
        }
        ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase_codes')
    op.drop_table('ea_acts')
    op.drop_table('ministries') 
    op.drop_table('federal_involvements') 
    op.drop_table('sub_sectors')
    op.drop_table('sectors')
    op.drop_table('proponents')
    op.drop_table('regions')
    # ### end Alembic commands ###