"""correction to work phase name

Revision ID: 73868272c32c
Revises: eb68451694da
Create Date: 2024-01-31 13:36:22.419454

"""
import sqlalchemy as sa
from alembic import op

from api.models.work_phase import WorkPhase
from api.models.work_type import WorkTypeEnum


# revision identifiers, used by Alembic.
revision = "73868272c32c"
down_revision = "eb68451694da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tables = WorkPhase.metadata.tables
    work_phase_table = tables["work_phases"]
    replace_func = sa.func.regexp_replace(
        work_phase_table.c.name,  # column
        "EAC Assessment Intake",  # str to replace
        "Pre-Early Engagement",  # str to replace with
    )
    op.execute(
        work_phase_table.update()
        .values({work_phase_table.c.name: replace_func})
        .where(work_phase_table.c.name.ilike(r"%EAC Assessment Intake%"))
    )
    conn = op.get_bind()
    phase_query = f"SELECT id FROM phase_codes WHERE name = 'Amendment Procedures' and work_type_id={WorkTypeEnum.AMENDMENT.value}"
    phase = conn.execute(sa.text(phase_query)).fetchone()
    work_phases_query = f"SELECT id from work_phases WHERE phase_id = {phase.id}"
    work_phases = conn.execute(sa.text(work_phases_query)).scalars().all()
    event_configuration_table = tables["event_configurations"]
    replace_func = sa.func.regexp_replace(
        event_configuration_table.c.name, "Assessment", "Amendment"
    )
    op.execute(
        event_configuration_table.update()
        .values({event_configuration_table.c.name: replace_func})
        .where(
            event_configuration_table.c.name.ilike(r"%assessment%"),
            event_configuration_table.c.work_phase_id.in_(work_phases),
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
