"""change works.current_phase_id to current_work_phase_id

Revision ID: 74e3f8a6b3c2
Revises: 74531216e674
Create Date: 2023-11-13 12:22:25.189428

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '74e3f8a6b3c2'
down_revision = '74531216e674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE works RESTART IDENTITY CASCADE")
    op.execute("TRUNCATE calendar_events RESTART IDENTITY CASCADE")

    with op.batch_alter_table('work_issue_updates', schema=None) as batch_op:
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('work_issue_updates_history', schema=None) as batch_op:
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_work_phase_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('works_current_phase_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'work_phases', ['current_work_phase_id'], ['id'])
        batch_op.drop_column('current_phase_id')

    with op.batch_alter_table('works_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_work_phase_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('works_history_current_phase_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'work_phases', ['current_work_phase_id'], ['id'])
        batch_op.drop_column('current_phase_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_phase_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('works_history_current_phase_id_fkey', 'phase_codes', ['current_phase_id'], ['id'])
        batch_op.drop_column('current_work_phase_id')

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_phase_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('works_current_phase_id_fkey', 'phase_codes', ['current_phase_id'], ['id'])
        batch_op.drop_column('current_work_phase_id')

    with op.batch_alter_table('work_issue_updates_history', schema=None) as batch_op:
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('work_issue_updates', schema=None) as batch_op:
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
