"""linked_works table name change

Revision ID: 7ef1104f2a2d
Revises: 13ab3f617dc2
Create Date: 2024-06-04 14:31:00.134222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ef1104f2a2d'
down_revision = '13ab3f617dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_works',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_work_id', sa.Integer(), nullable=False),
    sa.Column('linked_work_id', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['linked_work_id'], ['works.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['source_work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('LinkedWorks')
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.alter_column('last_active_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('staffs_history', schema=None) as batch_op:
        batch_op.alter_column('last_active_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs_history', schema=None) as batch_op:
        batch_op.alter_column('last_active_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               autoincrement=False)

    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.alter_column('last_active_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('LinkedWorks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"LinkedWorks_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('source_work_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('linked_work_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['linked_work_id'], ['works.id'], name='LinkedWorks_linked_work_id_fkey'),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], name='LinkedWorks_source_event_id_fkey'),
    sa.ForeignKeyConstraint(['source_work_id'], ['works.id'], name='LinkedWorks_source_work_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='LinkedWorks_pkey')
    )
    op.drop_table('linked_works')
    # ### end Alembic commands ###
