"""add IAAC as responsibility

Revision ID: 87cef5c064d8
Revises: f554f142190f
Create Date: 2024-07-16 14:06:55.546973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cef5c064d8'
down_revision = 'f554f142190f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO responsibilities(name, is_active, is_deleted) VALUES('IAAC', true, false)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM responsibilities WHERE name = 'IAAC'")
    # ### end Alembic commands ###
