"""Add unique constraint to projects abbreviation

Revision ID: 88b0bbb53b72
Revises: 03791c319e2b
Create Date: 2023-12-05 11:34:09.723702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b0bbb53b72'
down_revision = '03791c319e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_projects_abbreviation', ['abbreviation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_projects_abbreviation', type_='unique')
    # ### end Alembic commands ###
