"""remove escape character from office/analyst

Revision ID: a1d0edc67d25
Revises: c01c7c36064c
Create Date: 2023-03-13 08:34:22.920740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d0edc67d25'
down_revision = 'c01c7c36064c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE roles set name='Officer / Analyst', updated_by='u1' where name='Officer \/ Analyst'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
