"""staff_id removed from engagement

Revision ID: a85a39851cab
Revises: 99dd99e4dbbc
Create Date: 2022-07-21 21:01:30.719175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85a39851cab'
down_revision = '99dd99e4dbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('engagements_staff_id_fkey', 'engagements', type_='foreignkey')
    op.drop_column('engagements', 'staff_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagements', sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('engagements_staff_id_fkey', 'engagements', 'staffs', ['staff_id'], ['id'])
    # ### end Alembic commands ###
