"""set boolean fields nullable false

Revision ID: b16296e64a0f
Revises: 0f32217af693
Create Date: 2023-02-21 10:42:04.472210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16296e64a0f'
down_revision = '0f32217af693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Updating existing null values before marking fields not nullable.
    op.execute('UPDATE engagements SET is_active=true WHERE is_active IS NULL')
    op.alter_column('engagements', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE engagements SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('engagements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE events SET is_active=true WHERE is_active IS NULL')
    op.alter_column('events', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='t')
    op.execute('UPDATE events SET is_complete=false WHERE is_complete IS NULL')
    op.alter_column('events', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE events SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('events', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE indigenous_categories SET is_active=true WHERE is_active IS NULL')
    op.alter_column('indigenous_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='t')
    op.execute('UPDATE indigenous_categories SET is_deleted=true WHERE is_deleted IS NULL')
    op.alter_column('indigenous_categories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE indigenous_nations SET is_active=true WHERE is_active IS NULL')
    op.alter_column('indigenous_nations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE indigenous_nations SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('indigenous_nations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='f')
    op.execute('UPDATE indigenous_works SET is_active=true WHERE is_active IS NULL')
    op.alter_column('indigenous_works', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE indigenous_works SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('indigenous_works', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE inspection_attachments SET is_active=true WHERE is_active IS NULL')
    op.alter_column('inspection_attachments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE inspection_attachments SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('inspection_attachments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE inspection_attendees SET is_active=true WHERE is_active IS NULL')
    op.alter_column('inspection_attendees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE inspection_attendees SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('inspection_attendees', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE inspection_details SET is_active=true WHERE is_active IS NULL')
    op.alter_column('inspection_details', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE inspection_details SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('inspection_details', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE inspections SET is_active=true WHERE is_active IS NULL')
    op.alter_column('inspections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE inspections SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('inspections', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE issues SET is_key_issue=false WHERE is_key_issue IS NULL')
    op.alter_column('issues', 'is_key_issue',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE issues SET is_sensitive=false WHERE is_sensitive IS NULL')
    op.alter_column('issues', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE issues SET is_active=true WHERE is_active IS NULL')
    op.alter_column('issues', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='t')
    op.execute('UPDATE issues SET is_resolved=false WHERE is_resolved IS NULL')
    op.alter_column('issues', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE issues SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('issues', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE milestones SET is_active=true WHERE is_active IS NULL')
    op.alter_column('milestones', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE milestones SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('milestones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE milestones SET auto=false WHERE auto IS NULL')
    op.alter_column('milestones', 'auto',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE organizations SET is_active=true WHERE is_active IS NULL')
    op.alter_column('organizations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='t')
    op.execute('UPDATE organizations SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('organizations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE outcomes SET is_active=true WHERE is_active IS NULL')
    op.alter_column('outcomes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE outcomes SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('outcomes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE outcomes SET terminates_work=false WHERE terminates_work IS NULL')
    op.alter_column('outcomes', 'terminates_work',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE projects SET is_active=true WHERE is_active IS NULL')
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE projects SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('projects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE projects SET is_project_closed=false WHERE is_project_closed IS NULL')
    op.alter_column('projects', 'is_project_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE proponents SET is_active=true WHERE is_active IS NULL')
    op.alter_column('proponents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='t')
    op.execute('UPDATE proponents SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('proponents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE reminder_configurations SET is_active=true WHERE is_active IS NULL')
    op.alter_column('reminder_configurations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE reminder_configurations SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('reminder_configurations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE staff_work_roles SET is_active=true WHERE is_active IS NULL')
    op.alter_column('staff_work_roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE staff_work_roles SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('staff_work_roles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE staffs SET is_active=true WHERE is_active IS NULL')
    op.alter_column('staffs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='t')
    op.execute('UPDATE staffs SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('staffs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE work_engagements SET is_active=true WHERE is_active IS NULL')
    op.alter_column('work_engagements', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE work_engagements SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('work_engagements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE work_phases SET is_active=true WHERE is_active IS NULL')
    op.alter_column('work_phases', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE work_phases SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('work_phases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    op.execute('UPDATE work_statuses SET is_active=true WHERE is_active IS NULL')
    op.alter_column('work_statuses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               server_default='t')
    op.execute('UPDATE work_statuses SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('work_statuses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE works SET is_pecp_required=false WHERE is_pecp_required IS NULL')
    op.alter_column('works', 'is_pecp_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE works SET is_cac_recommended=false WHERE is_cac_recommended IS NULL')
    op.alter_column('works', 'is_cac_recommended',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE works SET is_active=true WHERE is_active IS NULL')
    op.alter_column('works', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='t')
    op.execute('UPDATE works SET is_completed=false WHERE is_completed IS NULL')
    op.alter_column('works', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='f')
    op.execute('UPDATE works SET is_deleted=false WHERE is_deleted IS NULL')
    op.alter_column('works', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               server_default='f')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('works', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('works', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('works', 'is_cac_recommended',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('works', 'is_pecp_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('work_statuses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('work_statuses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('work_phases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('work_phases', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('work_engagements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('work_engagements', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('staffs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('staffs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('staff_work_roles', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('staff_work_roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('reminder_configurations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('reminder_configurations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('proponents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('proponents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('projects', 'is_project_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('projects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('outcomes', 'terminates_work',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('outcomes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('outcomes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('organizations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('organizations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('milestones', 'auto',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('milestones', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('milestones', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('issues', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('issues', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('issues', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('issues', 'is_sensitive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('issues', 'is_key_issue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('inspections', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('inspections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('inspection_details', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('inspection_details', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('inspection_attendees', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('inspection_attendees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('inspection_attachments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('inspection_attachments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('indigenous_works', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('indigenous_works', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('indigenous_nations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('indigenous_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('events', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('events', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('events', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('engagements', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('engagements', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
