"""adding decision date in work

Revision ID: bd77ab52f918
Revises: 74e3f8a6b3c2
Create Date: 2023-11-14 21:55:50.820118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd77ab52f918'
down_revision = '74e3f8a6b3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_decision_date', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('works_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_decision_date', sa.DateTime(timezone=True), autoincrement=False, nullable=True))
    op.execute("INSERT INTO actions(name)VALUES('ChangePhaseEndEvent')")
    op.execute("INSERT INTO actions(name)VALUES('SetFederalInvolvement')")
    op.execute("INSERT INTO positions(name,sort_order)VALUES('PA/AA',7)")
    op.execute("INSERT INTO positions(name,sort_order)VALUES('IPE',8)")
    op.execute("INSERT INTO positions(name,sort_order)VALUES('HR',9)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_history', schema=None) as batch_op:
        batch_op.drop_column('work_decision_date')

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('work_decision_date')

    # ### end Alembic commands ###
