"""adding SUGGESTED in visibility enum

Revision ID: cb80bd4fe249
Revises: 498c9e7f50b6
Create Date: 2024-03-11 19:52:22.422861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb80bd4fe249'
down_revision = '498c9e7f50b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter type eventtemplatevisibilityenum add value 'SUGGESTED' after 'HIDDEN'")
    with op.batch_alter_table('action_configurations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'outcome_configurations', ['outcome_configuration_id'], ['id'])

    with op.batch_alter_table('special_fields_history', schema=None) as batch_op:
        batch_op.drop_index('entity_field_history_index')
        batch_op.drop_index('entity_field_index')
        batch_op.create_index('entity_field_index', ['entity', 'entity_id', 'field_name', 'time_range'], unique=False)

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.alter_column('simple_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.alter_column('simple_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('special_fields_history', schema=None) as batch_op:
        batch_op.drop_index('entity_field_index')
        batch_op.create_index('entity_field_history_index', ['entity', 'entity_id', 'field_name', 'time_range'], unique=False)

    with op.batch_alter_table('action_configurations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
