"""Remove pin from indigenous_works

Revision ID: eb68451694da
Revises: 8e57d2651837
Create Date: 2024-01-25 14:16:36.539628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb68451694da'
down_revision = '8e57d2651837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indigenous_works', 'pin', schema=None)
    op.drop_column('indigenous_works_history', 'pin', schema=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indigenous_works_history', sa.Column('pin', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('indigenous_works', sa.Column('pin', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.execute("UPDATE indigenous_works SET pin = 'Yes' WHERE indigenous_consultation_level_id = (SELECT id FROM indigenous_consultation_levels WHERE name = 'PIN')")
    op.execute("UPDATE indigenous_works_history SET pin = 'Yes' WHERE indigenous_consultation_level_id = (SELECT id FROM indigenous_consultation_levels WHERE name = 'PIN')")

    # ### end Alembic commands ###
