"""add milestone reference to work_engagements

Revision ID: f2071dc275f4
Revises: e81a9bcad31d
Create Date: 2022-07-18 19:19:56.601130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2071dc275f4'
down_revision = 'e81a9bcad31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_engagements', sa.Column('milestone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'work_engagements', 'milestones', ['milestone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_engagements', type_='foreignkey')
    op.drop_column('work_engagements', 'milestone_id')
    # ### end Alembic commands ###
