apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  config.js: |-
    // runtime-config.js vars
      window["_env_"] =  {
        "ENV": "dev",
        "NODE_ENV": "production",
        "REACT_APP_API_URL": "{{ .Values.app.api}}",
        "REACT_APP_KEYCLOAK_URL": "{{ .Values.keycloak.url }}",
        "REACT_APP_KEYCLOAK_CLIENT": "{{ .Values.keycloak.client }}",
        "REACT_APP_ENV": "{{ .Values.app.env }}",
      }