apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Chart.Name }}
  annotations:
    deployment.kubernetes.io/revision: "{{ .Release.Revision }}"
    checksum/image: {{ include "epictrack-web.imageHash" . }}
    checksum/config: {{ include "epictrack-web.configHash" . }}
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
      annotations:
        checksum/image: {{ include "epictrack-web.imageHash" . }}
        checksum/config: {{ include "epictrack-web.configHash" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/{{ tpl .Values.image.name . }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: {{ .Values.resources.cpu.limit }}
            memory: {{ .Values.resources.memory.limit }}
          requests:
            cpu: {{ .Values.resources.cpu.request }}
            memory: {{ .Values.resources.memory.request }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: {{ .Values.mountPath }}
          name: {{ .Chart.Name }}
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Chart.Name }}
        name: {{ .Chart.Name }}
