apiVersion: v1
kind: Service
metadata:
  annotations: null
  creationTimestamp: null
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: "8080"
    port: {{ .Values.service.port}}
    targetPort: 8080
  selector:
    app: {{ .Values.app.name }}
status:
  loadBalancer: {}
