
export const WORK_STATE = Object.freeze({
    SUSPENDED: "SUSPENDED",
    IN_PROGRESS: "IN_PROGRESS",
    WITHDRAWN: "WITHDRAWN",
    TERMINATED: "TERMINATED",
    CLOSED: "CLOSED",
    COMPLETED: "COMPLETED",   
});
