# Author: Yichun Zhao
version: "3.7"
services:
  eao-reports-api-db:
    container_name: eao-reports-api-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${CAMUNDA_JDBC_DB_NAME:-reports-db}
    volumes:
      - ./postgres/reports-db:/var/lib/postgresql/data
    ports:
      - '8432:5432'
    restart: unless-stopped
    networks:
      - eao-network

  eao-reports-api:
    container_name: eao-reports-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - eao-reports-api-db
    ports:
      - '3002:8080'
    environment:
      - JWT_OIDC_ISSUER:${JWT_OIDC_ISSUER}
      - JWT_OIDC_WELL_KNOWN_CONFIG:${JWT_OIDC_WELL_KNOWN_CONFIG}
      - JWT_OIDC_ALGORITHMS:${JWT_OIDC_ALGORITHMS:-RS256}
      - JWT_OIDC_AUDIENCE:${JWT_OIDC_AUDIENCE:-forms-flow-web}
      - JWT_OIDC_CLIENT_SECRET:${JWT_OIDC_CLIENT_SECRET}
      - JWT_OIDC_JWKS_CACHE_TIMEOUT:${JWT_OIDC_JWKS_CACHE_TIMEOUT:-300}
      - PYTHONWARNINGS:${PYTHONWARNINGS:-'once'}
      - DATABASE_USERNAME:${DATABASE_USERNAME}
      - DATABASE_PASSWORD:${DATABASE_PASSWORD}
      - DATABASE_NAME:${DATABASE_NAME}
      - DATABASE_HOST:${DATABASE_HOST}
      - DATABASE_PORT:${DATABASE_PORT}
      - FLASK_APP:${FLASK_APP:-wsgi.py}
      - FLASK_ENV:${FLASK_ENV:-'production'}
      - FLASK_DEBUG:${FLASK_DEBUG:-false}
      - POD_TESTING:${POD_TESTING:-false}
      - SQLALCHEMY_ECHO:${SQLALCHEMY_ECHO:-false}
      - CACHE_TIMEOUT:${CACHE_TIMEOUT:-300}

    networks:
      - eao-network
    

networks:
  eao-network:
    driver: "bridge"

volumes:
  postgres:
