apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: web-build-template
  annotations:
    description: "Build Configuration Template for the MET WEB Project"
    tags: "met, web, reactjs, typescript, jest"
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: ${APP}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${APP}
      labels:
        app: ${APP}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${APP}:latest'
      resources:
        limits:
          cpu: 1500m
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 2Gi
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      postCommit: {}
      source:
        type: Git
        git:
          uri: ${GITHUB_REPO}
          ref: develop
        contextDir: ${GITHUB_CONTEXT_DIR}
      triggers:
        - type: ConfigChange
      runPolicy: Serial
parameters:
  - name: APP
    description: "The application name"
    value: epictrack-web
  - name: GITHUB_REPO
    description: "The github repo uri"
    value: 'https://github.com/bcgov/EPIC-FLOW.git'
  - name: GITHUB_CONTEXT_DIR
    description: "The repository folder context"
    value: /epictrack-web
