replicaCount: 1

image:
  repository: epictrack-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "prod"

resources:
  cpu:
    limit: 250m
    request: 150m
  memory:
    limit: 512Mi
    request: 350Mi

database:
  secret: epictrack-patroni
  service:
    name: epictrack-patroni
    port: 5432



service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epictrack-web
    cacheEnabled: true
    issuer: https://loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://loginproxy.gov.bc.ca
    realm: eao-epic
    adminClientId: realm-management
    adminClientSecret: 76885nOZnMv1hKs9fTkU0Y3ivDFDK5wI
python:
  pythonBuffered: 1
  connectTimeout: 60
cdogs:  
  tokenEndpoint: https://loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
  apiEndpoint: https://cdogs-test.api.gov.bc.ca/api/v2
  clientId: 29305A8F-A6B8D86FB9F
  clientSecret: d5f94ee3-5875-4bca-a85a-da4ed2f7946f
