"""work_phase in configuration

Revision ID: 6f3b95392d4e
Revises: d50e4a0afa8c
Create Date: 2023-09-16 22:33:04.900282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3b95392d4e'
down_revision = 'd50e4a0afa8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_phase_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'work_phases', ['work_phase_id'], ['id'])

    with op.batch_alter_table('event_configurations_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_phase_id', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(None, 'work_phases', ['work_phase_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_configurations_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('work_phase_id')

    with op.batch_alter_table('event_configurations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('work_phase_id')

    # ### end Alembic commands ###
