"""adding_responsibilities

Revision ID: 0016fbf1f81b
Revises: 198282402cf9
Create Date: 2023-07-04 11:12:54.094035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0016fbf1f81b'
down_revision = '198282402cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    responsible = op.create_table('responsibilities',
                                  sa.Column('created_by', sa.String(length=255), nullable=True),
                                  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
                                  sa.Column('updated_by', sa.String(length=255), nullable=True),
                                  sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                                  sa.Column('is_active', sa.Boolean(), server_default='t', nullable=False),
                                  sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False),
                                  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                  sa.Column('name', sa.String(), nullable=True),
                                  sa.PrimaryKeyConstraint('id')
                                  )
    op.bulk_insert(responsible,[
        {
            "name": "EAO"
        },
        {
            "name": "Proponent"
        },
        {
            "name": "TAC"
        },
        {
            "name": "PIN"
        },
        {
            "name": "Indigenous Group"
        },
        {
            "name": "Communications"
        },
        {
            "name": "Legal"
        },
        {
            "name": "Minister's Office"
        },
        {
            "name": "Other"
        },
    ])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('responsibilities')
    # ### end Alembic commands ###
