"""rename sectors and sub sectors

Revision ID: 07fc96f3340b
Revises: 29c3dd058444
Create Date: 2023-01-18 10:42:23.005485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07fc96f3340b"
down_revision = "29c3dd058444"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    types_table = op.create_table(
        "types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    sub_types_table = op.create_table(
        "sub_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.bulk_insert(
        types_table,
        [
            {"name": "Energy - Electricity", "short_name": "Energy"},
            {"name": "Energy - Oil and Natural Gas", "short_name": "O&G"},
            {"name": "Industrial", "short_name": "Industry"},
            {"name": "Mines", "short_name": "Mines"},
            {"name": "Tourist Destination Resort", "short_name": "Resorts"},
            {"name": "Transportation", "short_name": "Transport"},
            {"name": "Waste Disposal", "short_name": "Waste"},
            {"name": "Water Management", "short_name": "Water"},
            {"name": "Other", "short_name": "Other"},
        ],
    )
    op.bulk_insert(
        sub_types_table,
        [
            {"name": "Power Plants", "short_name": "Plant", "type_id": 1},
            {"name": "Transmission Lines", "short_name": "Lines", "type_id": 1},
            {"name": "Storage Facilities", "short_name": "Storage", "type_id": 2},
            {"name": "Oil Refineries", "short_name": "Refinery", "type_id": 2},
            {"name": "Processing Plants", "short_name": "Proccesing", "type_id": 2},
            {"name": "Pipelines", "short_name": "Pipeline", "type_id": 2},
            {"name": "Offshore Facilities", "short_name": "Offshore", "type_id": 2},
            {
                "name": "Organic and Inorganic Chemicals",
                "short_name": "Chemicals",
                "type_id": 3,
            },
            {"name": "Primary Metals", "short_name": "Metals", "type_id": 3},
            {
                "name": "Non-metallic Mineral Products",
                "short_name": "Non-Metallic",
                "type_id": 3,
            },
            {"name": "Forest Products", "short_name": "Forest", "type_id": 3},
            {"name": "Other Industries", "short_name": "Other", "type_id": 3},
            {"name": "Coal Mines", "short_name": "Coal", "type_id": 4},
            {"name": "Mineral Mines", "short_name": "Mineral", "type_id": 4},
            {"name": "Sand and Gravel Pits", "short_name": "Gravel", "type_id": 4},
            {"name": "Placer Mineral Mines", "short_name": "Placer", "type_id": 4},
            {
                "name": "Construction Stone/Industrial Minerals",
                "short_name": "Stone",
                "type_id": 4,
            },
            {"name": "Offshore Mines", "short_name": "Offshore", "type_id": 4},
            {"name": "Resort Developments", "short_name": "Resort", "type_id": 5},
            {"name": "Golf Resorts", "short_name": "Golf", "type_id": 5},
            {"name": "Marina Resorts", "short_name": "Marina", "type_id": 5},
            {"name": "Ski Resorts", "short_name": "Ski", "type_id": 5},
            {"name": "Public Highways", "short_name": "Highway", "type_id": 6},
            {"name": "Railways", "short_name": "Railway", "type_id": 6},
            {"name": "Ferry Terminals", "short_name": "Ferry", "type_id": 6},
            {"name": "Marine Ports", "short_name": "Port", "type_id": 6},
            {"name": "Airports", "short_name": "Airport", "type_id": 6},
            {
                "name": "Hazardous Waste Management",
                "short_name": "Hazardous",
                "type_id": 7,
            },
            {"name": "Solid Waste Management", "short_name": "Solid", "type_id": 7},
            {"name": "Liquid Waste Management", "short_name": "Liquid", "type_id": 7},
            {"name": "Dams", "short_name": "Dams", "type_id": 8},
            {"name": "Dikes", "short_name": "Dikes", "type_id": 8},
            {"name": "Water Diversion", "short_name": "Diversion", "type_id": 8},
            {
                "name": "Groundwater Extraction",
                "short_name": "Groundwater",
                "type_id": 8,
            },
            {
                "name": "Shoreline Modification",
                "short_name": "Shoreline",
                "type_id": 8,
            },
            {"name": "Other", "short_name": "Other", "type_id": 9},
        ],
    )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column("sub_sector_id", new_column_name="sub_type_id")
        batch_op.drop_constraint("projects_sub_sector_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(None, "sub_types", ["sub_type_id"], ["id"])

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.alter_column(
            "responsible_epd_id", new_column_name="relationship_holder_id"
        )
        batch_op.drop_constraint(
            "organizations_responsible_epd_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "staffs", ["relationship_holder_id"], ["id"])

    op.drop_table("sub_sectors")
    op.drop_table("sectors")

    positions = sa.table(
        "positions",
        sa.Column("name", sa.String(), nullable=False),
    )
    op.bulk_insert(positions, [{"name": "Minster"}])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    sector = op.create_table(
        "sectors",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('sectors_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("short_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="sectors_pkey"),
        postgresql_ignore_search_path=False,
    )
    sub_sector = op.create_table(
        "sub_sectors",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("sector_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("short_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["sector_id"], ["sectors.id"], name="sub_sectors_sector_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="sub_sectors_pkey"),
    )
    op.bulk_insert(
        sector,
        [
            {"name": "Energy - Electricity", "short_name": "Energy"},
            {"name": "Energy - Oil and Natural Gas", "short_name": "O&G"},
            {"name": "Industrial", "short_name": "Industry"},
            {"name": "Mines", "short_name": "Mines"},
            {"name": "Tourist Destination Resort", "short_name": "Resorts"},
            {"name": "Transportation", "short_name": "Transport"},
            {"name": "Waste Disposal", "short_name": "Waste"},
            {"name": "Water Management", "short_name": "Water"},
            {"name": "Other", "short_name": "Other"},
        ],
    )
    op.bulk_insert(
        sub_sector,
        [
            {"name": "Power Plants", "short_name": "Plant", "sector_id": 1},
            {"name": "Transmission Lines", "short_name": "Lines", "sector_id": 1},
            {"name": "Storage Facilities", "short_name": "Storage", "sector_id": 2},
            {"name": "Oil Refineries", "short_name": "Refinery", "sector_id": 2},
            {"name": "Processing Plants", "short_name": "Proccesing", "sector_id": 2},
            {"name": "Pipelines", "short_name": "Pipeline", "sector_id": 2},
            {"name": "Offshore Facilities", "short_name": "Offshore", "sector_id": 2},
            {
                "name": "Organic and Inorganic Chemicals",
                "short_name": "Chemicals",
                "sector_id": 3,
            },
            {"name": "Primary Metals", "short_name": "Metals", "sector_id": 3},
            {
                "name": "Non-metallic Mineral Products",
                "short_name": "Non-Metallic",
                "sector_id": 3,
            },
            {"name": "Forest Products", "short_name": "Forest", "sector_id": 3},
            {"name": "Other Industries", "short_name": "Other", "sector_id": 3},
            {"name": "Coal Mines", "short_name": "Coal", "sector_id": 4},
            {"name": "Mineral Mines", "short_name": "Mineral", "sector_id": 4},
            {"name": "Sand and Gravel Pits", "short_name": "Gravel", "sector_id": 4},
            {"name": "Placer Mineral Mines", "short_name": "Placer", "sector_id": 4},
            {
                "name": "Construction Stone/Industrial Minerals",
                "short_name": "Stone",
                "sector_id": 4,
            },
            {"name": "Offshore Mines", "short_name": "Offshore", "sector_id": 4},
            {"name": "Resort Developments", "short_name": "Resort", "sector_id": 5},
            {"name": "Golf Resorts", "short_name": "Golf", "sector_id": 5},
            {"name": "Marina Resorts", "short_name": "Marina", "sector_id": 5},
            {"name": "Ski Resorts", "short_name": "Ski", "sector_id": 5},
            {"name": "Public Highways", "short_name": "Highway", "sector_id": 6},
            {"name": "Railways", "short_name": "Railway", "sector_id": 6},
            {"name": "Ferry Terminals", "short_name": "Ferry", "sector_id": 6},
            {"name": "Marine Ports", "short_name": "Port", "sector_id": 6},
            {"name": "Airports", "short_name": "Airport", "sector_id": 6},
            {
                "name": "Hazardous Waste Management",
                "short_name": "Hazardous",
                "sector_id": 7,
            },
            {"name": "Solid Waste Management", "short_name": "Solid", "sector_id": 7},
            {"name": "Liquid Waste Management", "short_name": "Liquid", "sector_id": 7},
            {"name": "Dams", "short_name": "Dams", "sector_id": 8},
            {"name": "Dikes", "short_name": "Dikes", "sector_id": 8},
            {"name": "Water Diversion", "short_name": "Diversion", "sector_id": 8},
            {
                "name": "Groundwater Extraction",
                "short_name": "Groundwater",
                "sector_id": 8,
            },
            {
                "name": "Shoreline Modification",
                "short_name": "Shoreline",
                "sector_id": 8,
            },
            {"name": "Other", "short_name": "Other", "sector_id": 9},
        ],
    )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column("sub_type_id", new_column_name="sub_sector_id")
        batch_op.drop_constraint("projects_sub_type_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            "projects_sub_sector_id_fkey", "sub_sectors", ["sub_sector_id"], ["id"]
        )
    op.drop_table("sub_types")
    op.drop_table("types")
    # ### end Alembic commands ###
