"""inspection

Revision ID: 0915ec6f0b2c
Revises: 1c211e88093a
Create Date: 2022-03-28 16:05:51.692928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0915ec6f0b2c'
down_revision = '1c211e88093a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ea_certificate', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'ea_certificate')
    # ### end Alembic commands ###
