"""adding ea_act_id to task_template

Revision ID: 198282402cf9
Revises: 31d30597cc58
Create Date: 2023-06-20 14:10:47.700263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198282402cf9'
down_revision = '31d30597cc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ea_act_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'ea_acts', ['ea_act_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ea_act_id')

    # ### end Alembic commands ###
