"""adding foreign keys for work_calendar_event,events

Revision ID: 2245335bd765
Revises: 2025a1d522b3
Create Date: 2023-08-01 10:55:33.614508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2245335bd765'
down_revision = '2025a1d522b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE work_calendar_events_history RESTART IDENTITY CASCADE')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_configuration_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'event_configurations', ['event_configuration_id'], ['id'])

    with op.batch_alter_table('events_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_configuration_id', sa.Integer(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(None, 'event_configurations', ['event_configuration_id'], ['id'])

    with op.batch_alter_table('work_calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_configuration_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'event_configurations', ['event_configuration_id'], ['id'])

    with op.batch_alter_table('work_calendar_events_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_configuration_id', sa.Integer(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(None, 'event_configurations', ['event_configuration_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_calendar_events_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_configuration_id')

    with op.batch_alter_table('work_calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_configuration_id')

    with op.batch_alter_table('events_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_configuration_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_configuration_id')

    # ### end Alembic commands ###
