"""reminder_configurations

Revision ID: 27cdce23d103
Revises: 4f89baa1d849
Create Date: 2023-02-13 20:37:17.686655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cdce23d103'
down_revision = '4f89baa1d849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_configurations',
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reminder_type', sa.String(length=255), nullable=False),
    sa.Column('interval', sa.Text(), nullable=False),
    sa.Column('email_addresses', sa.Text(), nullable=False),
    sa.Column('reminder_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_configurations')
    # ### end Alembic commands ###
