"""adding notes to events

Revision ID: 3173b6880321
Revises: 9b111b53327b
Create Date: 2023-09-05 15:47:22.116419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3173b6880321'
down_revision = '9b111b53327b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))

    with op.batch_alter_table('events_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_history', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
