"""correcting spelling issues in tasks, task_events

Revision ID: 4755ad027428
Revises: 6c784cb24718
Create Date: 2023-07-04 12:38:09.633734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4755ad027428'
down_revision = '6c784cb24718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsibility_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('task_events_responsiblity_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'responsibilities', ['responsibility_id'], ['id'])
        batch_op.drop_column('responsible_entity')
        batch_op.drop_column('responsiblity_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsibility_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('tasks_responsiblity_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'responsibilities', ['responsibility_id'], ['id'])
        batch_op.drop_column('responsiblity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsiblity_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_responsiblity_id_fkey', 'responsibilities', ['responsiblity_id'], ['id'])
        batch_op.drop_column('responsibility_id')

    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsiblity_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('responsible_entity', postgresql.ENUM('Proponent', 'PIN', 'EAO', 'Federal Agencies', name='responsibleentityenum'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_events_responsiblity_id_fkey', 'responsibilities', ['responsiblity_id'], ['id'])
        batch_op.drop_column('responsibility_id')

    # ### end Alembic commands ###
