"""added column report_title to work_types

Revision ID: 4c2d3191f8f4
Revises: a1d0edc67d25
Create Date: 2023-03-30 14:47:50.037547

"""
import json

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4c2d3191f8f4"
down_revision = "a1d0edc67d25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ea_acts",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "ea_acts",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("ea_acts", "sort_order", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "eao_teams",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "eao_teams",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "eao_teams", "sort_order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "federal_involvements",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "federal_involvements",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "federal_involvements", "sort_order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "indigenous_nations", "sort_order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "milestone_types",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "milestone_types",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "milestone_types", "sort_order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "ministries",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "ministries",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "ministries", "sort_order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "phase_codes",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "phase_codes",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "positions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "positions",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "positions", "sort_order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "proponents", "sort_order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "regions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "regions",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("regions", "sort_order", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "roles",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "roles",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("roles", "sort_order", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "sub_types",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "sub_types",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "sub_types", "sort_order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "substitution_acts",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "substitution_acts",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "substitution_acts", "sort_order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "types",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "types",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("types", "sort_order", existing_type=sa.INTEGER(), nullable=False)
    op.add_column("work_types", sa.Column("report_title", sa.String(), nullable=True))
    op.alter_column(
        "work_types",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "work_types",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )

    work_types = [
        {"name": "Project Notification", "report_title": "Project Notification"},
        {"name": r"Minister''s Designation", "report_title": "Project Designation Request"},
        {"name": r"CEAO''s Designation", "report_title": "Project Designation Request"},
        {"name": "Intake (Pre-EA)", "report_title": "Intake (Pre-EA)"},
        {"name": "Exemption Order", "report_title": "Exemption Order Request"},
        {"name": "Assessment", "report_title": "EA Certificate Request"},
        {"name": "Simple Amendment", "report_title": "EAC/Order Amendment"},
        {"name": "Typical Amendment", "report_title": "EAC/Order Amendment"},
        {"name": "Complex Amendment", "report_title": "EAC/Order Amendment"},
        {"name": "Post-EAC Document Review", "report_title": "Post-Decision Plan Review"},
        {"name": "EAC Extension", "report_title": "EAC Extension Request"},
        {"name": "Substantial Start Decision", "report_title": "Substantial Start Decision"},
        {"name": "EAC/Order Transfer", "report_title": "EAC/Order Transfer"},
        {"name": "EAC/Order Suspension", "report_title": "EAC/Order Suspension"},
        {"name": "EAC/Order Cancellation", "report_title": "EAC/Order Cancellation"},
        {"name": "Other", "report_title": "Other EAO Work"},
    ]
    op.execute(
        """
        UPDATE work_types set report_title = work_type.report_title FROM (
            SELECT  * FROM json_populate_recordset(null::work_types,'%s')
        ) work_type
        WHERE work_types.name = work_type.name
        """
        % json.dumps(work_types)
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_types",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "work_types",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.drop_column("work_types", "report_title")
    op.alter_column("types", "sort_order", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "types",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "types",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "substitution_acts", "sort_order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "substitution_acts",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "substitution_acts",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "sub_types", "sort_order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "sub_types",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "sub_types",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column("roles", "sort_order", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "roles",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "roles",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column("regions", "sort_order", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "regions",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "regions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "proponents", "sort_order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "positions", "sort_order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "positions",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "positions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "phase_codes",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "phase_codes",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "ministries", "sort_order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "ministries",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "ministries",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "milestone_types", "sort_order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "milestone_types",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "milestone_types",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "indigenous_nations", "sort_order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "federal_involvements", "sort_order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "federal_involvements",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "federal_involvements",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "eao_teams", "sort_order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "eao_teams",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "eao_teams",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column("ea_acts", "sort_order", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "ea_acts",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "ea_acts",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    # ### end Alembic commands ###
