"""PIN and workPhase tables

Revision ID: 63a7a6914464
Revises: 29157766cb41
Create Date: 2022-03-02 10:04:47.365257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a7a6914464'
down_revision = '29157766cb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    eao_team = op.create_table('eao_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ind_category = op.create_table('indigenous_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ind_group = op.create_table('indigenous_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indigenous_works',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('indigenous_group_id', sa.Integer(), nullable=False),
    sa.Column('indigenous_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indigenous_category_id'], ['indigenous_categories.id'], ),
    sa.ForeignKeyConstraint(['indigenous_group_id'], ['indigenous_groups.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('anticipated_end_date', sa.DateTime(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phase_codes.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('works', sa.Column('eao_team_id', sa.Integer(), nullable=False))
    op.drop_constraint('works_eoa_team_id_fkey', 'works', type_='foreignkey')
    op.create_foreign_key(None, 'works', 'eao_teams', ['eao_team_id'], ['id'])
    op.drop_column('works', 'eoa_team_id')
    op.drop_table('eoa_teams')


    op.bulk_insert(eao_team, [{
            "name" : "CIAR"
        },
        {
            "name" : "MMT"
        },
        {
            "name" : "O&G"
        },
        {
            "name" : "PIWWIM"
        },
        {
            "name" : "Other"
        }]
    )
    op.bulk_insert(ind_category, [{
            "name" : "Notification",
            "sort_order" : 1,
            "is_active" : True
        },
        {
            "name" : "Working Group",
            "sort_order" : 2,
            "is_active" : True
        },
        {
            "name" : "Collaboration",
            "sort_order" : 3,
            "is_active" : True
        },
        {
            "name" : "Consultation Agreement",
            "sort_order" : 4,
            "is_active" : False
        },
        {
            "name" : "Consent Required",
            "sort_order" : 5,
            "is_active" : True
        },
        {
            "name" : "Other",
            "sort_order" : 6,
            "is_active" : True
        }
    ])
    op.bulk_insert(ind_group, [
        {
            'name': "?Akisq'nuk First Nation (Columbia Lake Indian Band)",
            'is_active': True
        },
        {
            'name': "?Aq'am (St. Mary's Indian Band)",
            'is_active': True
        },
        {
            'name': '?Esdilagh First Nation (Alexandria Indian Band)',
            'is_active': True
        },
        {
            'name': '‘Namgis First Nation',
            'is_active': True
        },
        {
            'name': 'Acho Dene Koe First Nation',
            'is_active': True
        },
        {
            'name': 'Adams Lake Indian Band',
            'is_active': True
        },
        {
            'name': 'Ahousaht First Nation',
            'is_active': True
        },
        {
            'name': 'Aitchelitz Band',
            'is_active': True
        },
        {
            'name': 'Ashcroft Indian Band',
            'is_active': True
        },
        {
            'name': 'Binche Whut’en First Nation',
            'is_active': True
        },
        {
            'name': 'Blueberry River First Nations',
            'is_active': True
        },
        {
            'name': 'Bonaparte Indian Band',
            'is_active': True
        },
        {
            'name': 'Boothroyd Indian Band',
            'is_active': True
        },
        {
            'name': 'Boston Bar First Nation',
            'is_active': True
        },
        {
            'name': 'Carcross/Tagish First Nation',
            'is_active': True
        },
        {
            'name': 'Carrier Chilcotin Tribal Council',
            'is_active': True
        },
        {
            'name': 'Carrier Sekani Tribal Council',
            'is_active': True
        },
        {
            'name': 'Champagne and Aishihik First Nations',
            'is_active': True
        },
        {
            'name': 'Chawathil Band (Hope)',
            'is_active': True
        },
        {
            'name': 'Cheam First Nation',
            'is_active': True
        },
        {
            'name': 'Cheslatta Carrier Nation',
            'is_active': True
        },
        {
            'name': 'Clinton / Whispering Pines Indian Band',
            'is_active': True
        },
        {
            'name': 'Coastal First Nations',
            'is_active': True
        },
        {
            'name': 'Coldwater Indian Band',
            'is_active': True
        },
        {
            'name': "Cook's Ferry Indian Band",
            'is_active': True
        },
        {
            'name': 'Cowichan Tribes',
            'is_active': True
        },
        {
            'name': "Da'naxda'xw/Awaetlala First Nation",
            'is_active': True
        },
        {
            'name': 'Daylu Dene Nation (Lower Post)',
            'is_active': True
        },
        {
            'name': 'Dease River Band Council',
            'is_active': True
        },
        {
            'name': "Denetsaa Tse K'Nai (Prophet River Band)",
            'is_active': True
        },
        {
            'name': 'Ditidaht First Nation',
            'is_active': True
        },
        {
            'name': 'Doig River First Nation',
            'is_active': True
        },
        {
            'name': 'Dzawada’enuxw First Nation',
            'is_active': True
        },
        {
            'name': 'Ehattesaht First Nation',
            'is_active': True
        },
        {
            'name': "Esk'etemc First Nation",
            'is_active': True
        },
        {
            'name': 'Esquimalt Nation',
            'is_active': True
        },
        {
            'name': 'Fort Nelson First Nation',
            'is_active': True
        },
        {
            'name': 'Fraser Thompson Indian Services Society',
            'is_active': True
        },
        {
            'name': 'Gingolx Village Government (Kincolith)',
            'is_active': True
        },
        {
            'name': 'Gitanmaax Band Council',
            'is_active': True
        },
        {
            'name': 'Gitanyow Hereditary Chiefs',
            'is_active': True
        },
        {
            'name': "Gitga'at First Nation (Hartley Bay)",
            'is_active': True
        },
        {
            'name': 'Gitksan Local Government Services Society',
            'is_active': True
        },
        {
            'name': "Gitlaxt'aamix Village Government (New Aiyansh)",
            'is_active': True
        },
        {
            'name': 'Gitsegukla Indian Band (Kitsegugkla)',
            'is_active': True
        },
        {
            'name': 'Gitwangak Band Council (Kitwanga)',
            'is_active': True
        },
        {
            'name': 'Gitwinksihlkw Village Government',
            'is_active': True
        },
        {
            'name': 'Gitxaala Nation (Kitkatla)',
            'is_active': True
        },
        {
            'name': 'Gitxsan',
            'is_active': True
        },
        {
            'name': "Gwa'sala-'Nakwaxda'xw Nation",
            'is_active': True
        },
        {
            'name': 'Gwawaenuk Tribe',
            'is_active': True
        },
        {
            'name': 'Hagwilget Village Council',
            'is_active': True
        },
        {
            'name': 'Haida Nation, Council of the',
            'is_active': True
        },
        {
            'name': 'Haisla Nation (Kitimaat Village Council)',
            'is_active': True
        },
        {
            'name': 'Halalt First Nation',
            'is_active': True
        },
        {
            'name': 'Halfway River First Nations',
            'is_active': True
        },
        {
            'name': 'Heiltsuk Nation (Bella Bella Indian Band)',
            'is_active': True
        },
        {
            'name': 'Hesquiaht First Nation',
            'is_active': True
        },
        {
            'name': 'High Bar First Nation',
            'is_active': True
        },
        {
            'name': 'Homalco (Xwemalhkwu) Indian Band',
            'is_active': True
        },
        {
            'name': "Hul'qumi'num Treaty Group",
            'is_active': True
        },
        {
            'name': 'Hupacasath First Nation',
            'is_active': True
        },
        {
            'name': 'Huu-ay-aht First Nation',
            'is_active': True
        },
        {
            'name': 'Iskut First Nation',
            'is_active': True
        },
        {
            'name': 'K’ómoks (Comox) First Nation',
            'is_active': True
        },
        {
            'name': "Ka:'yu:'k't'h'/Che:k:tles7et'h' First Nation (Kyoquot)",
            'is_active': True
        },
        {
            'name': 'Kanaka Bar Indian Band',
            'is_active': True
        },
        {
            'name': 'Kaska Dena Council',
            'is_active': True
        },
        {
            'name': 'Katzie First Nation',
            'is_active': True
        },
        {
            'name': 'Kispiox Band Council',
            'is_active': True
        },
        {
            'name': "Kitasoo/Xai'xais Band Council (Klemtu)",
            'is_active': True
        },
        {
            'name': 'Kitselas First Nation',
            'is_active': True
        },
        {
            'name': 'Kitsumkalum First Nation',
            'is_active': True
        },
        {
            'name': 'Klahoose First Nation',
            'is_active': True
        },
        {
            'name': 'Ktunaxa Nation',
            'is_active': True
        },
        {
            'name': 'Kwadacha Nation',
            'is_active': True
        },
        {
            'name': 'Kwakiutl District Council',
            'is_active': True
        },
        {
            'name': 'Kwakiutl Indian Band',
            'is_active': True
        },
        {
            'name': 'Kwantlen First Nation',
            'is_active': True
        },
        {
            'name': 'Kwaw-kwaw-a-pilt First Nation',
            'is_active': True
        },
        {
            'name': 'Kwiakah First Nations',
            'is_active': True
        },
        {
            'name': "Kwikwasut'inuxw Haxwa'mis First Nation",
            'is_active': True
        },
        {
            'name': 'Kwikwetlem First Nation',
            'is_active': True
        },
        {
            'name': 'Laich-Kwil-Tach Treaty Society',
            'is_active': True
        },
        {
            'name': 'Lake Babine Nation ',
            'is_active': True
        },
        {
            'name': 'Lake Cowichan First Nation',
            'is_active': True
        },
        {
            'name': "Laxgalts'ap Village Government",
            'is_active': True
        },
        {
            'name': "Laxkw'alaams Indian Band",
            'is_active': True
        },
        {
            'name': "Leq'a:mel First Nation (Lakahahmen)",
            'is_active': True
        },
        {
            'name': "Lheidli-T'enneh First Nation",
            'is_active': True
        },
        {
            'name': "Lhoosk'uz Dene' Government Administration (Kluskus)",
            'is_active': True
        },
        {
            'name': 'Lhtako Dene Nation (Red Bluff)',
            'is_active': True
        },
        {
            'name': 'Liard First Nation',
            'is_active': True
        },
        {
            'name': "Lil'wat Nation (Mount Currie Indian Band)",
            'is_active': True
        },
        {
            'name': 'Little Shuswap Lake Indian Band',
            'is_active': True
        },
        {
            'name': 'Lower Nicola Indian Band',
            'is_active': True
        },
        {
            'name': 'Lower Similkameen Indian Band',
            'is_active': True
        },
        {
            'name': "Lower Stl'atl'imx Tribal Council",
            'is_active': True
        },
        {
            'name': 'Lyackson First Nation',
            'is_active': True
        },
        {
            'name': 'Lytton First Nation',
            'is_active': True
        },
        {
            'name': 'Maa-nulth First Nations',
            'is_active': True
        },
        {
            'name': 'Malahat Indian Band',
            'is_active': True
        },
        {
            'name': 'Mamalilikulla First Nation',
            'is_active': True
        },
        {
            'name': 'Matsqui First Nation',
            'is_active': True
        },
        {
            'name': 'McLeod Lake Indian Band',
            'is_active': True
        },
        {
            'name': 'Metlakatla First Nation',
            'is_active': True
        },
        {
            'name': 'Mowachaht/Muchalaht First Nation',
            'is_active': True
        },
        {
            'name': "Musgamagw Dzawada'enuxw Tribal Council",
            'is_active': True
        },
        {
            'name': 'Musqueam Indian Band',
            'is_active': True
        },
        {
            'name': "Nadleh Whut'en Band (Fraser Lake)",
            'is_active': True
        },
        {
            'name': "Nak'azdli Band",
            'is_active': True
        },
        {
            'name': 'Nanwakolas Council',
            'is_active': True
        },
        {
            'name': "Naut'sa mawt Tribal Council (Alliance Tribal Council)",
            'is_active': True
        },
        {
            'name': 'Nazko First Nation',
            'is_active': True
        },
        {
            'name': 'Nee-Tahi-Buhn Band',
            'is_active': True
        },
        {
            'name': 'Neskonlith Indian Band',
            'is_active': True
        },
        {
            'name': 'Nicola Tribal Association',
            'is_active': True
        },
        {
            'name': 'Nicomen Indian Band',
            'is_active': True
        },
        {
            'name': "Nisga'a Nation",
            'is_active': True
        },
        {
            'name': "Nlaka'pamux First Nations",
            'is_active': True
        },
        {
            'name': "Nlaka'pamux Nation Tribal Council",
            'is_active': True
        },
        {
            'name': 'Nooaitch Indian Band',
            'is_active': True
        },
        {
            'name': 'Northern Regional Negotiations Table',
            'is_active': True
        },
        {
            'name': 'Northern Shuswap Tribal Council (Northern Secwepemc te Qelmucw)',
            'is_active': True
        },
        {
            'name': "N'Quatqua Band (Anderson Lake)",
            'is_active': True
        },
        {
            'name': 'Nuchatlaht First Nation',
            'is_active': True
        },
        {
            'name': 'Nuu-chah-nulth Tribal Council',
            'is_active': True
        },
        {
            'name': 'Nuxalk Nation (Bella Coola Band)',
            'is_active': True
        },
        {
            'name': 'Nxwisten (Bridge River Indian Band)',
            'is_active': True
        },
        {
            'name': 'Okanagan Indian Band',
            'is_active': True
        },
        {
            'name': 'Okanagan Nation Alliance',
            'is_active': True
        },
        {
            'name': 'Old Masset Village Council',
            'is_active': True
        },
        {
            'name': 'Oregon Jack Creek Band',
            'is_active': True
        },
        {
            'name': 'Osoyoos Indian Band',
            'is_active': True
        },
        {
            'name': 'Pacheedaht First Nation',
            'is_active': True
        },
        {
            'name': 'Pauquachin First Nation',
            'is_active': True
        },
        {
            'name': 'Penelakut Indian Band',
            'is_active': True
        },
        {
            'name': 'Penticton Indian Band',
            'is_active': True
        },
        {
            'name': 'Peters Band',
            'is_active': True
        },
        {
            'name': 'Popkum Indian Band',
            'is_active': True
        },
        {
            'name': 'Qayqayt First Nation (New Westminister)',
            'is_active': True
        },
        {
            'name': 'Qualicum First Nation',
            'is_active': True
        },
        {
            'name': 'Quatsino First Nation',
            'is_active': True
        },
        {
            'name': 'Ross River Dene Council',
            'is_active': True
        },
        {
            'name': "Saik'uz First Nation",
            'is_active': True
        },
        {
            'name': 'Samahquam First Nation',
            'is_active': True
        },
        {
            'name': 'Saulteau First Nations',
            'is_active': True
        },
        {
            'name': "Sc'ianew (Cheanuh) First Nation (Beecher Bay)",
            'is_active': True
        },
        {
            'name': 'Seabird Island Indian Band',
            'is_active': True
        },
        {
            'name': "Sekw'el'was (Cayoose Creek Band)",
            'is_active': True
        },
        {
            'name': 'Semiahmoo First Nation',
            'is_active': True
        },
        {
            'name': 'Seton Lake Band',
            'is_active': True
        },
        {
            'name': 'Shackan Indian Band',
            'is_active': True
        },
        {
            'name': 'shíshálh Nation (Sechelt First Nation)',
            'is_active': True
        },
        {
            'name': 'Shuswap Band',
            'is_active': True
        },
        {
            'name': 'Shuswap Nation Tribal Council',
            'is_active': True
        },
        {
            'name': 'Shxwhá:y Village (Skway)',
            'is_active': True
        },
        {
            'name': "Shxw'ow'hamel First Nation",
            'is_active': True
        },
        {
            'name': 'Sik-e-Dakh (Glen Vowell Indian Band)',
            'is_active': True
        },
        {
            'name': 'Simpcw First Nation (North Thompson River)',
            'is_active': True
        },
        {
            'name': 'Siska Indian Band',
            'is_active': True
        },
        {
            'name': 'Skatin Nations (Skookumchuck)',
            'is_active': True
        },
        {
            'name': 'Skatin Samahquam Negotiations Inc. (formally In-SHUCK-ch Nation) ',
            'is_active': True
        },
        {
            'name': 'Skawahlook First Nation',
            'is_active': True
        },
        {
            'name': "Skeetchestn Indian Band (Deadman's Creek)",
            'is_active': True
        },
        {
            'name': 'Skidegate Band Council',
            'is_active': True
        },
        {
            'name': 'Skin Tyee Band',
            'is_active': True
        },
        {
            'name': 'Skowkale First Nation',
            'is_active': True
        },
        {
            'name': 'Skuppah Indian Band',
            'is_active': True
        },
        {
            'name': 'Skwah First Nation',
            'is_active': True
        },
        {
            'name': "Sliammon First Nation (Tla'amin)",
            'is_active': True
        },
        {
            'name': 'Snaw-naw-as (Nanoose First Nation)',
            'is_active': True
        },
        {
            'name': 'Snaw-Naw-As First Nation',
            'is_active': True
        },
        {
            'name': 'Snuneymuxw First Nation',
            'is_active': True
        },
        {
            'name': 'Songhees First Nation',
            'is_active': True
        },
        {
            'name': 'Soowahlie Indian Band',
            'is_active': True
        },
        {
            'name': 'Southern Dakelh Nation Alliance',
            'is_active': True
        },
        {
            'name': 'Spallumcheen (Splatsin) Band',
            'is_active': True
        },
        {
            'name': 'Spuzzum First Nation',
            'is_active': True
        },
        {
            'name': "Sq'éwlets (Scowlitz) First Nation",
            'is_active': True
        },
        {
            'name': 'Squamish Nation',
            'is_active': True
        },
        {
            'name': 'Squiala First Nation',
            'is_active': True
        },
        {
            'name': "St'át'imc Chiefs Council (Lillooet Tribal Council)",
            'is_active': True
        },
        {
            'name': "Stellat'en First Nation",
            'is_active': True
        },
        {
            'name': 'Stó:lo Nation',
            'is_active': True
        },
        {
            'name': 'Stó:lo Tribal Council',
            'is_active': True
        },
        {
            'name': 'Sto:lo Xwexwilmexw Treaty Association ',
            'is_active': True
        },
        {
            'name': 'Sts’ailes Nation (Chehalis Indian Band)',
            'is_active': True
        },
        {
            'name': "Stswecem'c Xgat'tem First Nation (Canoe Creek Indian Band)",
            'is_active': True
        },
        {
            'name': "Stz'uminus First Nation (Chemainus)",
            'is_active': True
        },
        {
            'name': 'Sumas First Nation',
            'is_active': True
        },
        {
            'name': 'Tahltan Band Council',
            'is_active': True
        },
        {
            'name': 'Tahltan Central Council',
            'is_active': True
        },
        {
            'name': 'Takla Nation',
            'is_active': True
        },
        {
            'name': 'Taku River Tlingit First Nation (Atlin First Nation)',
            'is_active': True
        },
        {
            'name': "Te'mexw Treaty Association",
            'is_active': True
        },
        {
            'name': 'Teslin Tlingit Council',
            'is_active': True
        },
        {
            'name': "T'it'q'et (Lillooet Indian Band)",
            'is_active': True
        },
        {
            'name': "Tk'emlúps te Secwepemc (Kamloops)",
            'is_active': True
        },
        {
            'name': "Tla'amin Nation (Sliammon)",
            'is_active': True
        },
        {
            'name': 'Tla-o-qui-aht First Nation (Clayoquot)',
            'is_active': True
        },
        {
            'name': 'Tlatlasikwala First Nation',
            'is_active': True
        },
        {
            'name': "Tl'azt'en Nation",
            'is_active': True
        },
        {
            'name': "Tl'etinqox-t'in Government Office (Anaham Indian Band)",
            'is_active': True
        },
        {
            'name': 'Tlowitsis Nation',
            'is_active': True
        },
        {
            'name': 'Tobacco Plains Indian Band',
            'is_active': True
        },
        {
            'name': "Toosey Indian Band (Tl'esqox)",
            'is_active': True
        },
        {
            'name': 'Toquaht First Nation',
            'is_active': True
        },
        {
            'name': 'Treaty 8 First Nations',
            'is_active': True
        },
        {
            'name': 'Ts’elxwéyeqw Tribe Society (Ch-ihl-kway-uhk First Nations)',
            'is_active': True
        },
        {
            'name': 'Tsartlip First Nation',
            'is_active': True
        },
        {
            'name': 'Tsawataineuk Indian Band (Dzawada’enuxw)',
            'is_active': True
        },
        {
            'name': 'Tsawout First Nation',
            'is_active': True
        },
        {
            'name': 'Tsawwassen First Nation',
            'is_active': True
        },
        {
            'name': 'Tsay Keh Dene',
            'is_active': True
        },
        {
            'name': 'Tseshaht First Nation',
            'is_active': True
        },
        {
            'name': 'Tsetsaut / Skii km Lax Ha Nation',
            'is_active': True
        },
        {
            'name': 'Tseycum First Nation',
            'is_active': True
        },
        {
            'name': 'Tsi Del Del (Alexis Creek First Nation)',
            'is_active': True
        },
        {
            'name': "Ts'il Kaz Koh (Burns Lake Indian Band)",
            'is_active': True
        },
        {
            'name': "Tsilhqot'in National Government",
            'is_active': True
        },
        {
            'name': 'Tsimshian First Nations Treaty Society',
            'is_active': True
        },
        {
            'name': "Ts'kw'aylaxw First Nation",
            'is_active': True
        },
        {
            'name': 'Tsleil-Waututh First Nation (Burrard Band)',
            'is_active': True
        },
        {
            'name': "T'Sou-ke Nation (Sooke)",
            'is_active': True
        },
        {
            'name': "Tsq'escen’ (Canim Lake Indian Band)",
            'is_active': True
        },
        {
            'name': 'Tzeachten First Nation',
            'is_active': True
        },
        {
            'name': 'Uchucklesaht Tribe',
            'is_active': True
        },
        {
            'name': 'Ucluelet First Nation',
            'is_active': True
        },
        {
            'name': 'Ulkatcho First Nation',
            'is_active': True
        },
        {
            'name': 'Union Bar Indian Band',
            'is_active': True
        },
        {
            'name': 'Upper Nicola Band',
            'is_active': True
        },
        {
            'name': 'Upper Similkameen Indian Band',
            'is_active': True
        },
        {
            'name': 'We Wai Kai Nation (Cape Mudge Indian Band)',
            'is_active': True
        },
        {
            'name': 'Wei Wai Kum First Nation (Campbell River Indian Band)',
            'is_active': True
        },
        {
            'name': 'West Moberly First Nations',
            'is_active': True
        },
        {
            'name': 'Westbank First Nation',
            'is_active': True
        },
        {
            'name': "Wet'suwet'en First Nation",
            'is_active': True
        },
        {
            'name': "Wet'suwet'en Society, Office of",
            'is_active': True
        },
        {
            'name': 'Whispering Pines / Clinton Indian Band',
            'is_active': True
        },
        {
            'name': 'Williams Lake First Nation',
            'is_active': True
        },
        {
            'name': 'Witset First Nation (Moricetown Band)',
            'is_active': True
        },
        {
            'name': 'Wuikinuxv First Nation (Oweekeno)',
            'is_active': True
        },
        {
            'name': 'Wuikinuxv Kitasoo Nuxalk Tribal Council',
            'is_active': True
        },
        {
            'name': 'Xa’xtsa (Douglas First Nation)',
            'is_active': True
        },
        {
            'name': "Xat'sull First Nation (Soda Creek)",
            'is_active': True
        },
        {
            'name': "Xaxli'p First Nation (Fountain)",
            'is_active': True
        },
        {
            'name': 'Xeni Gwet-in First Nations Government (Nemiah)',
            'is_active': True
        },
        {
            'name': 'Yakweakwioose First Nation ',
            'is_active': True
        },
        {
            'name': 'Yale First Nation',
            'is_active': True
        },
        {
            'name': 'Yaqan nu?kiy (Lower Kootenay Indian Band)',
            'is_active': True
        },
        {
            'name': 'Yekooche First Nation',
            'is_active': True
        },
        {
            'name': "Yunesit'in (Stone Indian Band)",
            'is_active': True
        }
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('eoa_team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.create_foreign_key('works_eoa_team_id_fkey', 'works', 'eoa_teams', ['eoa_team_id'], ['id'])
    op.drop_column('works', 'eao_team_id')
    op.create_table('eoa_teams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='eoa_teams_pkey')
    )
    op.drop_table('work_phases')
    op.drop_table('indigenous_works')
    op.drop_table('indigenous_groups')
    op.drop_table('indigenous_categories')
    op.drop_table('eao_teams')
    # ### end Alembic commands ###
