"""drop location

Revision ID: 78cea6d9f3d0
Revises: 21fd85babd34
Create Date: 2023-05-25 19:19:13.866646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cea6d9f3d0'
down_revision = '21fd85babd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
