"""template_uploaded flas added to work_phase

Revision ID: 7bb25f2d87a4
Revises: fc7f4d21d13a
Create Date: 2023-08-21 11:57:03.253125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb25f2d87a4'
down_revision = 'fc7f4d21d13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_phases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_uploaded', sa.Boolean(), nullable=True))

    with op.batch_alter_table('work_phases_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_uploaded', sa.Boolean(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_phases_history', schema=None) as batch_op:
        batch_op.drop_column('template_uploaded')

    with op.batch_alter_table('work_phases', schema=None) as batch_op:
        batch_op.drop_column('template_uploaded')

    # ### end Alembic commands ###
