"""template_id_added_event_configurations

Revision ID: 9f7db8cccb06
Revises: 7bb25f2d87a4
Create Date: 2023-08-29 15:23:26.102924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7db8cccb06'
down_revision = '7bb25f2d87a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'event_templates', ['template_id'], ['id'])

    with op.batch_alter_table('event_configurations_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(None, 'event_templates', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_configurations_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('template_id')

    with op.batch_alter_table('event_configurations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###
