"""outcomes

Revision ID: a5d5c1263bce
Revises: e9783faa5bb0
Create Date: 2022-03-03 18:47:49.684595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d5c1263bce'
down_revision = 'e9783faa5bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    outcome = op.create_table('outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('terminates_work', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('outcome_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'outcomes', ['outcome_id'], ['id'])

    op.bulk_insert(outcome, [
        {
            "name" : "Project Withdrawn",
            "milestone_id" : 6,
            "sort_order" : 3170,
            "terminates_work" : True
        },
        {
            "name" : "Project Termination",
            "milestone_id" : 9,
            "sort_order" : 3180,
            "terminates_work" : False
        },
        {
            "name" : "Revised DPD Ordered",
            "milestone_id" : 13,
            "sort_order" : 3190,
            "terminates_work" : False
        },
        {
            "name" : "Exemption Order Granted",
            "milestone_id" : 13,
            "sort_order" : 3200,
            "terminates_work" : False
        },
        {
            "name" : "Assessment Terminated",
            "milestone_id" : 13,
            "sort_order" : 3210,
            "terminates_work" : True
        },
        {
            "name" : "Project Enters the EA Process",
            "milestone_id" : 13,
            "sort_order" : 3220,
            "terminates_work" : False
        },
        {
            "name" : "Project Withdrawn",
            "milestone_id" : 20,
            "sort_order" : 3230,
            "terminates_work" : True
        },
        {
            "name" : "Project Termination",
            "milestone_id" : 23,
            "sort_order" : 3240,
            "terminates_work" : False
        },
        {
            "name" : "Project Withdrawn",
            "milestone_id" : 31,
            "sort_order" : 3250,
            "terminates_work" : True
        },
        {
            "name" : "Project Termination",
            "milestone_id" : 34,
            "sort_order" : 3260,
            "terminates_work" : False
        },
        {
            "name" : "Project Withdrawn",
            "milestone_id" : 39,
            "sort_order" : 3270,
            "terminates_work" : True
        },
        {
            "name" : "Project Withdrawn",
            "milestone_id" : 46,
            "sort_order" : 3280,
            "terminates_work" : True
        },
        {
            "name" : "EAC Granted",
            "milestone_id" : 50,
            "sort_order" : 3290,
            "terminates_work" : False
        },
        {
            "name" : "EAC Refused",
            "milestone_id" : 50,
            "sort_order" : 3300,
            "terminates_work" : False
        }
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'outcome_id')
    op.drop_table('outcomes')
    # ### end Alembic commands ###
