"""add column current_phase to works

Revision ID: af1a598657ad
Revises: a6ceb67a5e94
Create Date: 2022-03-17 10:11:31.928991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1a598657ad'
down_revision = 'a6ceb67a5e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('current_phase_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'works', 'phase_codes', ['current_phase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_column('works', 'current_phase_id')
    # ### end Alembic commands ###
