"""add column posted_date to work_statuses

Revision ID: b0b7e2536ab7
Revises: d9226e72e4ea
Create Date: 2023-01-20 10:06:05.228232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b7e2536ab7'
down_revision = 'd9226e72e4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_statuses', sa.Column('posted_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_statuses', 'posted_date')
    # ### end Alembic commands ###
