"""remove start_at from task_events

Revision ID: b7e53dd4b2f1
Revises: 02303c8d9ca8
Create Date: 2023-08-11 10:04:43.511032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e53dd4b2f1'
down_revision = '02303c8d9ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.drop_column('start_at')

    with op.batch_alter_table('task_events_history', schema=None) as batch_op:
        batch_op.drop_column('start_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_events_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_at', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_at', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
