"""events->outcome_id set default to null

Revision ID: bc81e1bb675c
Revises: f2cde86da016
Create Date: 2022-03-08 09:48:34.634771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc81e1bb675c'
down_revision = 'f2cde86da016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'outcome_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('outcomes', 'milestone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outcomes', 'milestone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'outcome_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
