"""rename events-> name to title

Revision ID: c0114b689c2a
Revises: bc81e1bb675c
Create Date: 2022-03-08 11:11:55.391593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0114b689c2a'
down_revision = 'bc81e1bb675c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_column('events', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('events', 'title')
    # ### end Alembic commands ###
