"""rename role caart to cairt

Revision ID: c01c7c36064c
Revises: b52650f8d0f1
Create Date: 2023-03-06 16:14:18.768373

"""
import json
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01c7c36064c'
down_revision = 'b52650f8d0f1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE roles SET name = 'FN CAIRT' where name = 'FN CAART'")
    phases = [{
        "name": "Early Engagement",
        "color": "#54858d"
    }, {
        "name": "Readiness Decision",
        "color": "#da6d65"
    }, {
        "name": "Process Planning",
        "color": "#043673"
    }, {
        "name": "Application Development & Review",
        "color": "#4d95d0"
    }, {
        "name": "Effects Assessment",
        "color": "#e7a913"
    },  {
        "name": "Recommendation",
        "color": "#e7a913"
    }, {
        "name": "Referral/Decision",
        "color": "#6a54a3"
    }]

    op.execute(
        """
        UPDATE phase_codes set color = phase.color FROM (
            SELECT  * FROM json_populate_recordset(null::phase_codes,'%s')
        ) phase
        WHERE phase_codes.name = phase.name
        """ % json.dumps(phases)
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
