"""remove_short_description_from_events

Revision ID: c404fbbd91d2
Revises: 6fd78c6511a4
Create Date: 2023-04-04 19:51:53.944725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c404fbbd91d2'
down_revision = '6fd78c6511a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'short_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('short_description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
