"""add new table substitution_acts new fields for PECP

Revision ID: c47ce735dc0e
Revises: 55d11c80ae81
Create Date: 2023-01-11 14:46:58.259095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c47ce735dc0e"
down_revision = "55d11c80ae81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    substitution_acts_table = op.create_table(
        "substitution_acts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("topic", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("explanation", sa.Text(), nullable=True))

    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("substitution_act_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            None, "substitution_acts", ["substitution_act_id"], ["id"]
        )
    op.bulk_insert(substitution_acts_table,[
        {
            'name': 'CEAA 2004'
        },
        {
            'name': 'CEAA 2012'
        },
        {
            'name': 'IAA (2019)'
        }
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("works", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("substitution_act_id")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("explanation")
        batch_op.drop_column("topic")

    op.drop_table("substitution_acts")
    # ### end Alembic commands ###
