"""removing description -event

Revision ID: d50e4a0afa8c
Revises: d7ba1b0b4e19
Create Date: 2023-09-15 18:56:51.731796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50e4a0afa8c'
down_revision = 'd7ba1b0b4e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2000), nullable=True))
        batch_op.drop_column('short_description')
        batch_op.drop_column('long_description')
        batch_op.drop_column('is_complete')

    with op.batch_alter_table('events_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2000), autoincrement=False, nullable=True))
        batch_op.drop_column('short_description')
        batch_op.drop_column('long_description')
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
