app:
  name: epictrack
  url: epictrack-web-c8b80a-prod.apps.gold.devops.gov.bc.ca
  api: https://epictrack-api-c8b80a-prod.apps.gold.devops.gov.bc.ca
  env: prod
resources:
  cpu:
    limit: 100m
    request: 80m
  memory:
    limit: 100Mi
    request: 80Mi
image:
  name: epictrack-web
  tag: prod
  repository: image-registry.openshift-image-registry.svc:5000/c8b80a-tools/
keycloak:
  url: "https://loginproxy.gov.bc.ca"
  realm: eao-epic
  client: epictrack-web
service:
  port: 8080
replicas:
  count: 1
mountPath: /usr/share/nginx/html/config/

