export interface WorkType {
  id: number;
  is_active: boolean;
  name: string;
}

export enum WorkTypeEnum {
  PROJECT_NOTIFICATION = 1,
  MINISTERS_DESIGNATION = 2,
  CEAOS_DESIGNATION = 3,
  INTAKE_PRE_EA = 4,
  EXEMPTION_ORDER = 5,
  ASSESSMENT = 6,
  AMENDMENT = 7,
  POST_EAC_DOCUMENT_REVIEW = 8,
  EAC_EXTENSION = 9,
  SUBSTANTIAL_START_DECISION = 10,
  EAC_ORDER_TRANSFER = 11,
  EAC_ORDER_SUSPENSION = 12,
  EAC_ORDER_CANCELLATION = 13,
  OTHER = 14,
  MATERIAL_ALTERATION = 15,
  JOINT_COMPLEX_AMENDMENT = 16,
}
