name: EPIC TRACK WEB CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "epictrack-web/**"
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash
    working-directory: ./epictrack-web

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    if: github.repository == 'saravanpa-aot/EPIC.track'

    steps:
      - uses: actions/checkout@v2
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Lint
        id: lint
        run: |
          npm run lint

  testing:
    needs: setup-job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: false
          browser: chrome
          headless: false
          install-command: npm install
          working-directory: ./epictrack-web

      # # Set codecov branch name with prefix if pull request
      # - name: Sets Codecov branch name
      #   run: |
      #     echo "CODECOV_BRANCH=PR_${{github.head_ref}}" >> $GITHUB_ENV
      #   if: github.event_name == 'pull_request'

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     flags: epictrackweb
      #     name: codecov-epictrack-web
      #     fail_ci_if_error: true
      #     verbose: true
      #     override_branch: ${{env.CODECOV_BRANCH}}
      #     token: ${{ secrets.CODECOV_TOKEN }}

  build-check:
    needs: setup-job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: build to check strictness
        id: build
        run: |
          npm run build --quiet || true
