name: EPIC TRACK WEB CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "epictrack-web/**"
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash
    working-directory: ./epictrack-web

jobs:
  setup-job:
    runs-on: ubuntu-latest

    if: github.repository == 'bcgov/EPIC.track'

    steps:
      - uses: actions/checkout@v2
      - run: "true"

  web-linting:
    needs: setup-job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        id: lint
        run: |
          npm run lint

  web-testing:
    needs: setup-job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Test with Cypress
        id: test
        run: |
          npx cypress run --component --headed --browser chrome

  web-build-check:
    needs: setup-job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: build to check strictness
        id: build
        run: |
          npm run build --quiet
